'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Building2,CheckCircle2,ChevronLeft,ChevronRight,CloudUpload,Database,ExternalLink,RefreshCcw,Save,Search,Settings2,ShieldAlert,Trash2,Users2,Wifi,WifiOff,X,Plus,MapPin,LockKeyhole} from 'lucide-react';
import * as XLSX from 'xlsx';
import {DEFAULT_PROVIDER_RULES} from '@/lib/superapp/automation';
import type {ProviderRule} from '@/lib/superapp/types';
import {getSupabase,upsertChunks} from '@/lib/superapp/supabase';

type Row={id:string;hotel_code?:string;title:string;city?:string;province?:string;caring_category?:string;cooperation_status?:string;provider?:string;pms?:string;capacity_total?:number;hotel_rate?:boolean;hotel_capacity?:boolean;rate_expert?:string;capacity_expert?:string;rate_api?:boolean;capacity_api?:boolean;rate_online?:boolean;capacity_online?:boolean;automation_score?:number;automation_status?:string;migration_needed?:boolean;replacement_provider?:string;grade?:string};
type Stats={all:number;online:number;capacity:number;rate:number;expert:number;offline:number;migrate:number};
type ExpertRow={expert_name:string;rate_hotels:number;capacity_hotels:number;total_hotels:number};
const emptyStats:Stats={all:0,online:0,capacity:0,rate:0,expert:0,offline:0,migrate:0};
const norm=(v:any)=>String(v??'').replace(/\u200c/g,' ').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim().toLowerCase();
const val=(r:any,names:string[])=>{for(const k of Object.keys(r)){if(names.some(n=>norm(n)===norm(k))&&String(r[k]??'').trim()!=='')return r[k]}return undefined};
const text=(r:any,names:string[])=>String(val(r,names)??'').trim();
const yes=(v:any)=>['1','true','yes','بله','فعال','online','بلی'].includes(norm(v));
const num=(v:any)=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
async function rowsFromFile(file:File){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('شیت قابل خواندن پیدا نشد');const rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:false}) as any[];if(!rows.length)throw new Error('فایل خالی است');return rows}

export default function HotelSuperApp({isSuperAdmin=false,actor,onCreateTask}:{isSuperAdmin?:boolean;actor?:{id?:string;username?:string;name?:string};onCreateTask?:(row:Row)=>void}){
 const [rows,setRows]=useState<Row[]>([]),[rules,setRules]=useState<ProviderRule[]>(DEFAULT_PROVIDER_RULES),[stats,setStats]=useState<Stats>(emptyStats),[experts,setExperts]=useState<ExpertRow[]>([]);
 const [tab,setTab]=useState('overview'),[q,setQ]=useState(''),[provider,setProvider]=useState('all'),[status,setStatus]=useState('all');
 const [page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[selected,setSelected]=useState<Row|null>(null);
 const debounce=useRef<any>(null); const pageSize=40;
 useEffect(()=>{void loadRules();void loadStats();void loadExperts()},[]);
 useEffect(()=>{if(!['hotels','fullyOnline','migration'].includes(tab))return;clearTimeout(debounce.current);debounce.current=setTimeout(()=>void loadPage(),250);return()=>clearTimeout(debounce.current)},[page,q,provider,status,tab]);
 async function loadRules(){const db=getSupabase();if(!db)return;const {data}=await db.from('ihos_provider_rules').select('*').order('priority');if(data?.length)setRules(data.map((x:any)=>({name:x.name,rateApi:x.rate_api,capacityApi:x.capacity_api,active:x.active,effectiveFrom:x.effective_from,replacementProvider:x.replacement_provider,priority:x.priority})))}
 async function loadStats(){const db=getSupabase();if(!db)return;const [{count},{data,error}]=await Promise.all([db.from('ihos_hotels').select('id',{count:'exact',head:true}),db.rpc('ihos_hotel_dashboard_stats')]);const analytic=(!error&&data?data:{}) as Partial<Stats>;setStats({...emptyStats,...analytic,all:count||0})}
 async function loadExperts(){const db=getSupabase();if(!db)return;const {data,error}=await db.from('ihos_expert_workload_v').select('*').order('total_hotels',{ascending:false});if(!error)setExperts((data||[]) as ExpertRow[])}
 async function loadPage(){const db=getSupabase();if(!db){setMsg('Supabase تنظیم نشده است');return}setBusy(true);try{let query:any=db.from('ihos_hotel_status_v').select('*',{count:'exact'});if(provider!=='all')query=query.eq('provider',provider);if(status!=='all')query=query.eq('automation_status',status);if(tab==='migration')query=query.eq('migration_needed',true);if(tab==='fullyOnline')query=query.eq('automation_status','۱۰۰٪ آنلاین');if(q.trim()){const s=q.trim().replace(/[%_,]/g,' ');query=query.or(`title.ilike.%${s}%,hotel_code.ilike.%${s}%,city.ilike.%${s}%,province.ilike.%${s}%,rate_expert.ilike.%${s}%,capacity_expert.ilike.%${s}%`)}const from=(page-1)*pageSize;const {data,error,count}=await query.order('title',{ascending:true}).range(from,from+pageSize-1);if(error)throw error;setRows((data||[]) as Row[]);setTotal(count||0);setMsg(`${(count||0).toLocaleString('fa-IR')} نتیجه`)}catch(e:any){setMsg(`خطای دریافت: ${e.message}`)}finally{setBusy(false)}}
 async function refresh(){await Promise.all([loadStats(),loadPage(),loadRules(),loadExperts()])}
 async function importHotels(file:File){setBusy(true);setMsg('در حال پردازش فایل هتل‌ها...');try{const data=await rowsFromFile(file);const now=Date.now();const mapped=data.map((r,i)=>{const code=text(r,['کد هتل','hotel_code','HotelCode','کدهتل']);return {id:code?`hotel-${code}`:`hotel-import-${now}-${i}`,hotel_code:code,title:text(r,['نام هتل','title','HotelName','نام']),country:text(r,['کشور']),province:text(r,['استان','province']),city:text(r,['شهر','city']),hotel_group:text(r,['گروه نوع هتل']),caring_category:text(r,['CaringCategory','caring_category']),hotel_type:text(r,['نوع هتل']),phone:text(r,['تلفن هتل']),reservation_phone:text(r,['تلفن رزرواسیون','تلن رزرواسیون']),capacity_total:num(val(r,['تعداد تخت','ظرفیت کلی هتل','ظرفیت','capacity_total'])),provider:text(r,['نام پروایدر','provider','Provider'])||'IHO Provider',pms:text(r,['PMS']),cooperation_status:text(r,['وضعیت همکاری','cooperation_status']),risk_status:text(r,['وضعیت ریسکی']),hotel_category:text(r,['دسته بندی هتل']),grade:text(r,['درجه هتل']),purchase_period:num(val(r,['دوره خرید'])),payment_period:num(val(r,['دوره پرداخت'])),status_end_date:text(r,['تاریخ پایان وضعیت']),status_start_date:text(r,['تاریخ شروع وضعیت']),contract_date:text(r,['تاریخ قرارداد']),site_visible:yes(val(r,['نمایش در سایت','site_visible'])),search_visible:yes(val(r,['نمایش در نتایج جستجو','search_visible']))}}).filter(x=>x.title&&x.hotel_code);if(!mapped.length)throw new Error('ستون نام هتل یا کد هتل شناسایی نشد');await upsertChunks('ihos_hotels',mapped,300);setMsg(`✅ ${mapped.length.toLocaleString('fa-IR')} هتل ذخیره شد`);setPage(1);await refresh()}catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}}
 async function importExperts(file:File){setBusy(true);setMsg('در حال تطبیق کارشناسان نرخ و ظرفیت...');try{const data=await rowsFromFile(file);const db=getSupabase();if(!db)throw new Error('Supabase تنظیم نشده');const all:any[]=[];for(let from=0;;from+=1000){const {data:h,error}=await db.from('ihos_hotels').select('id,hotel_code,title,provider').range(from,from+999);if(error)throw error;all.push(...(h||[]));if(!h||h.length<1000)break}const byCode=new Map(all.filter(x=>x.hotel_code).map(x=>[norm(x.hotel_code),x]));const byName=new Map<string,any[]>();all.forEach(h=>byName.set(norm(h.title),[...(byName.get(norm(h.title))||[]),h]));const patch=new Map<string,any>();let matched=0,unmatched=0;for(const r of data){const code=text(r,['کد هتل','hotel_code','HotelCode']);const hotelName=text(r,['نام هتل','HotelName','hotel_name']);const task=Number(val(r,['taskId','task id','task_id','TaskId']));const name=text(r,['First name','نام','کارشناس','expert_name','full_name']);if(!name||![1,2].includes(task))continue;let h=code?byCode.get(norm(code)):undefined;if(!h&&hotelName){const c=byName.get(norm(hotelName))||[];if(c.length===1)h=c[0]}if(!h){unmatched++;continue}const old=patch.get(h.id)||{id:h.id,hotel_id:h.id,hotel_code:h.hotel_code,provider:h.provider||'IHO Provider',hotel_rate:false,hotel_capacity:false,updated_at:new Date().toISOString()};if(task===1)old.capacity_expert=name;else old.rate_expert=name;patch.set(h.id,old);matched++}await upsertChunks('ihos_hotel_automation',[...patch.values()],300);setMsg(`✅ ${matched.toLocaleString('fa-IR')} تخصیص ثبت شد؛ ${unmatched.toLocaleString('fa-IR')} مورد تطبیق نشد`);await refresh()}catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}}
 async function destructiveAction(action:'delete-row'|'clear-table',table:string,id?:string,label?:string){if(!isSuperAdmin){setMsg('فقط سوپر ادمین مجاز به حذف اطلاعات است');return}if(!window.confirm(action==='clear-table'?`تمام ${label||table} حذف شود؟`:'این رکورد حذف شود؟'))return;let password='';if(action==='clear-table'){password=window.prompt('رمز حذف کامل داده‌ها را وارد کنید')||'';if(!password)return}setBusy(true);try{const res=await fetch('/api/admin/delete',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,table,id,password,actor:{...actor,isSuperAdmin:true}})});const out=await res.json();if(!res.ok)throw new Error(out.error||'عملیات حذف ناموفق بود');setMsg(`✅ ${out.deleted||1} رکورد حذف شد`);await refresh()}catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}}
 async function saveRules(){setBusy(true);try{await upsertChunks('ihos_provider_rules',rules.map(r=>({id:norm(r.name).replace(/\s+/g,'-'),name:r.name,rate_api:r.rateApi,capacity_api:r.capacityApi,active:r.active,effective_from:r.effectiveFrom||null,replacement_provider:r.replacementProvider||null,priority:r.priority,updated_at:new Date().toISOString()})),50);setMsg('قوانین Provider ذخیره شد');await refresh()}catch(e:any){setMsg(`خطا: ${e.message}`)}finally{setBusy(false)}}
 const providers=useMemo(()=>['all',...rules.map(r=>r.name)],[rules]);const pages=Math.max(1,Math.ceil(total/pageSize));const onlinePct=stats.all?Math.round(stats.online/stats.all*100):0;
 return <div className="hotelOS">
  <section className="hotelOsHero"><div><span className="eyebrow">IRANHOTEL SUPPLY OS</span><h1>مرکز مدیریت آنلاین‌سازی هتل‌ها</h1><p>تمرکز اصلی: منبع نرخ، منبع ظرفیت قابل فروش، Provider و میزان وابستگی هر هتل به کارشناس.</p></div><div className="heroScore"><strong>{onlinePct}٪</strong><span>۱۰۰٪ آنلاین واقعی</span><small>نرخ و ظرفیت بدون دخالت کارشناس</small></div></section>
  <div className="hotelOsTabs">{[['overview','نمای مدیریتی'],['hotels','پرونده هتل‌ها'],['fullyOnline','۱۰۰٪ آنلاین'],['experts','تحلیل کارشناسان'],['migration','پیشنهاد مهاجرت'],['providers','Providerها'],['settings','تنظیمات و ورود داده'],['governance','مدیریت داده']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setPage(1)}}>{l}</button>)}</div>
  {tab==='overview'&&<><div className="superKpis executiveKpis">{[[Building2,'کل هتل‌های دیتابیس',stats.all],[CheckCircle2,'۱۰۰٪ آنلاین',stats.online],[Wifi,'ظرفیت آنلاین',stats.capacity],[Activity,'نرخ آنلاین',stats.rate],[Users2,'وابسته به کارشناس',stats.expert],[ShieldAlert,'نیازمند مهاجرت',stats.migrate]].map(([I,l,v]:any)=><div className="superKpi" key={l}><I/><div><span>{l}</span><strong>{Number(v||0).toLocaleString('fa-IR')}</strong></div></div>)}</div><div className="hotelInsightGrid"><article className="insightCard"><h3>قاعده آنلاین بودن</h3><p>Providerهای Harris Netminder، Lamasoo، Adotel و Sepehr نرخ و ظرفیت را آنلاین می‌دهند.</p><p>Moghim و VHotel فقط ظرفیت را آنلاین می‌دهند.</p><p>در IHO Provider، آنلاین بودن براساس ثبت نرخ و ظرفیت توسط خود هتل یا کارشناس تعیین می‌شود.</p></article><article className="insightCard"><h3>تمرکز عملیاتی</h3><div className="opportunity"><strong>{stats.expert.toLocaleString('fa-IR')}</strong><span>هتل دارای دخالت کارشناس</span></div><div className="opportunity"><strong>{stats.migrate.toLocaleString('fa-IR')}</strong><span>هتل مناسب مهاجرت Provider</span></div></article></div></>}
  {['hotels','fullyOnline','migration'].includes(tab)&&<><div className="hotelToolbar"><div className="searchBox"><Search size={18}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="جستجوی نام، کد، شهر یا کارشناس..."/></div><select value={provider} onChange={e=>{setProvider(e.target.value);setPage(1)}}>{providers.map(x=><option key={x} value={x}>{x==='all'?'همه Providerها':x}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">همه وضعیت‌ها</option><option>۱۰۰٪ آنلاین</option><option>ظرفیت آنلاین</option><option>نرخ آنلاین</option><option>کارشناس‌محور</option><option>آفلاین</option></select><button className="btn ghost" onClick={refresh}><RefreshCcw size={16}/> تازه‌سازی</button></div><div className="hotelDataTable"><table><thead><tr><th>هتل</th><th>موقعیت</th><th>Provider</th><th>منبع نرخ</th><th>منبع ظرفیت</th><th>وضعیت آنلاین</th><th>اقدام پیشنهادی</th><th>عملیات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="hotelNameBtn" onClick={()=>setSelected(r)}><span>{r.title?.slice(0,1)}</span><div><b>{r.title}</b><small>کد {r.hotel_code||'—'} • {r.caring_category||'بدون Caring'}</small></div></button></td><td>{r.city||'—'}<small>{r.province||''}</small></td><td><b>{r.provider||'IHO Provider'}</b><small>{r.pms||''}</small></td><td><SourceBadge online={!!r.rate_online} expert={r.rate_expert} api={r.rate_api} hotel={r.hotel_rate}/></td><td><SourceBadge online={!!r.capacity_online} expert={r.capacity_expert} api={r.capacity_api} hotel={r.hotel_capacity}/></td><td><b>{r.automation_score||0}٪</b><small>{r.automation_status}</small></td><td>{r.migration_needed?<b className="migrationText">انتقال به {r.replacement_provider||'Provider آنلاین'}</b>:<span className="okText">بدون اقدام فوری</span>}</td><td><button className="btn ghost" onClick={()=>onCreateTask?.(r)}><Plus size={15}/> ایجاد تسک</button><button className="iconBtn" onClick={()=>setSelected(r)}><ExternalLink size={16}/></button>{isSuperAdmin&&<button className="iconBtn dangerBtn" onClick={()=>destructiveAction('delete-row','ihos_hotels',r.id)}><Trash2 size={16}/></button>}</td></tr>)}</tbody></table>{busy&&<div className="tableLoading">در حال دریافت داده…</div>}</div><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronRight/></button><span>صفحه {page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')} • {msg}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronLeft/></button></div></>}
  {tab==='experts'&&<div className="providerGrid">{experts.map(e=><article className="providerCard" key={e.expert_name}><header><div className="providerIcon">{e.expert_name.slice(0,1)}</div><div><h3>{e.expert_name}</h3><small>{e.total_hotels.toLocaleString('fa-IR')} هتل یکتا</small></div></header><div className="providerCapabilities"><span className="on">نرخ: {e.rate_hotels.toLocaleString('fa-IR')} هتل</span><span className="on">ظرفیت: {e.capacity_hotels.toLocaleString('fa-IR')} هتل</span></div></article>)}</div>}
  {tab==='providers'&&<div className="providerGrid">{rules.map(r=><article className="providerCard" key={r.name}><header><div className="providerIcon">{r.name.slice(0,2)}</div><div><h3>{r.name}</h3><small>{r.active?'فعال':'غیرفعال'}</small></div></header><div className="providerCapabilities"><span className={r.rateApi?'on':'off'}>{r.rateApi?<Wifi/>:<WifiOff/>} نرخ API</span><span className={r.capacityApi?'on':'off'}>{r.capacityApi?<Wifi/>:<WifiOff/>} ظرفیت API</span></div><p>جایگزین پیشنهادی: <b>{r.replacementProvider||'نیاز ندارد'}</b></p></article>)}</div>}
  {tab==='settings'&&<div className="settingsGrid"><article className="superCard"><h3><CloudUpload/> ورود فایل‌ها</h3><label className="uploadBox"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&importHotels(e.target.files[0])}/><Database/><div><b>خروجی BI هتل‌ها</b><small>اطلاعات پایه هتل‌ها در دیتابیس ذخیره می‌شود.</small></div></label><label className="uploadBox"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&importExperts(e.target.files[0])}/><Users2/><div><b>فایل کارشناسان</b><small>Task ID 1 = کارشناس ظرفیت، Task ID 2 = کارشناس نرخ</small></div></label><div className="importMsg">{msg||'فایل را انتخاب کن.'}</div></article><article className="superCard"><h3><Settings2/> ماتریس Provider</h3>{rules.map((r,i)=><div className="ruleRow" key={r.name}><input value={r.name} onChange={e=>setRules(x=>x.map((z,j)=>j===i?{...z,name:e.target.value}:z))}/><label><input type="checkbox" checked={r.rateApi} onChange={e=>setRules(x=>x.map((z,j)=>j===i?{...z,rateApi:e.target.checked}:z))}/> نرخ API</label><label><input type="checkbox" checked={r.capacityApi} onChange={e=>setRules(x=>x.map((z,j)=>j===i?{...z,capacityApi:e.target.checked}:z))}/> ظرفیت API</label><input type="date" value={r.effectiveFrom||''} onChange={e=>setRules(x=>x.map((z,j)=>j===i?{...z,effectiveFrom:e.target.value}:z))}/><input placeholder="Provider جایگزین" value={r.replacementProvider||''} onChange={e=>setRules(x=>x.map((z,j)=>j===i?{...z,replacementProvider:e.target.value}:z))}/></div>)}<button className="btn primary" onClick={saveRules}><Save/> ذخیره تنظیمات</button></article></div>}
  {tab==='governance'&&<div className="dataGovernance"><div className="governanceHero"><div><LockKeyhole/><div><h3>مرکز مدیریت داده</h3><p>حذف تکی بدون رمز و فقط با تأیید سوپر ادمین انجام می‌شود. حذف کامل هر ماژول نیازمند رمز تنظیم‌شده در تنظیمات سیستم است.</p></div></div></div><div className="dangerGrid">{[['ihos_hotels','اطلاعات هتل‌ها'],['ihos_hotel_automation','وضعیت نرخ و ظرفیت'],['ihos_provider_rules','قوانین Provider']].map(([t,l])=><article className="dangerCard" key={t}><Trash2/><div><h4>{l}</h4><p>پاک‌سازی کامل این ماژول از Supabase</p></div><button disabled={!isSuperAdmin} className="btn danger" onClick={()=>destructiveAction('clear-table',t,undefined,l)}>{isSuperAdmin?'حذف تمام داده‌ها':'فقط سوپر ادمین'}</button></article>)}</div></div>}
  {selected&&<HotelDrawer row={selected} close={()=>setSelected(null)} createTask={()=>onCreateTask?.(selected)}/>} 
 </div>
}
function SourceBadge({api,hotel,expert,online}:{api?:boolean;hotel?:boolean;expert?:string;online?:boolean}){return <div className={`sourceBadge ${online?'online':expert?'expert':'offline'}`}>{api?'Provider API':hotel?'هتل':expert?`کارشناس: ${expert}`:'آفلاین'}</div>}
function HotelDrawer({row,close,createTask}:{row:Row;close:()=>void;createTask:()=>void}){return <div className="drawerBackdrop" onClick={close}><aside className="hotelDrawer" onClick={e=>e.stopPropagation()}><button className="drawerClose" onClick={close}><X/></button><header><div className="drawerAvatar">{row.title?.slice(0,1)}</div><div><span className="eyebrow">HOTEL ONLINE PROFILE</span><h2>{row.title}</h2><p><MapPin size={15}/>{row.city||'—'}، {row.province||'—'}</p></div></header><button className="btn primary" onClick={createTask}><Plus size={16}/> ایجاد تسک برای این هتل</button><div className="drawerKpis"><div><Activity/><b>{row.automation_score||0}٪</b><span>آنلاین‌سازی</span></div><div><Building2/><b>{row.provider||'IHO Provider'}</b><span>Provider</span></div><div><CheckCircle2/><b>{row.automation_status||'—'}</b><span>وضعیت</span></div></div><section><h3>منبع نرخ و ظرفیت</h3><div className="connectionMap"><div><span>نرخ</span><SourceBadge api={row.rate_api} hotel={row.hotel_rate} expert={row.rate_expert} online={row.rate_online}/></div><i/><div><span>ظرفیت</span><SourceBadge api={row.capacity_api} hotel={row.hotel_capacity} expert={row.capacity_expert} online={row.capacity_online}/></div></div></section><section><h3>کارشناسان مرتبط</h3><dl><div><dt>کارشناس نرخ</dt><dd>{row.rate_expert||'هتل / Provider'}</dd></div><div><dt>کارشناس ظرفیت</dt><dd>{row.capacity_expert||'هتل / Provider'}</dd></div></dl></section>{row.migration_needed&&<section className="recommendation"><ShieldAlert/><div><b>پیشنهاد مهاجرت Provider</b><p>انتقال از {row.provider} به {row.replacement_provider||'Provider دارای API نرخ و ظرفیت'}.</p></div></section>}</aside></div>}
