'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,CheckCircle2,CloudUpload,Database,Filter,Hotel,RefreshCcw,Settings2,ShieldAlert,Users2,Save,ClipboardCheck,HeartHandshake} from 'lucide-react';
import * as XLSX from 'xlsx';
import {DEFAULT_PROVIDER_RULES,evaluateAutomation} from '@/lib/superapp/automation';
import type {HotelAutomation,ProviderRule} from '@/lib/superapp/types';
import {getSupabase,upsertChunks} from '@/lib/superapp/supabase';

type HotelRow={id:string;hotel_code?:string;title:string;city?:string;province?:string;country?:string;hotel_group?:string;caring_category?:string;hotel_type?:string;phone?:string;reservation_phone?:string;provider?:string;pms?:string;cooperation_status?:string;risk_status?:string;hotel_category?:string;grade?:string;site_visible?:boolean;search_visible?:boolean;capacity_total?:number;purchase_period?:number;payment_period?:number;status_start_date?:string;status_end_date?:string;contract_date?:string};
type Workflow={onlineStatus?:string;onlineOwner?:string;onlineBy?:string;onlineAt?:string;followUpOwner?:string;followUpAt?:string;careOwner?:string;careStatus?:string;careNextAt?:string;notes?:string};
const norm=(v:any)=>String(v??'').replace(/\u200c/g,' ').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim().toLowerCase();
const val=(r:any,names:string[])=>{const keys=Object.keys(r);for(const name of names){const hit=keys.find(k=>norm(k)===norm(name));if(hit!==undefined&&r[hit]!==undefined&&r[hit]!==null&&String(r[hit]).trim()!=='')return r[hit]}return undefined};
const text=(r:any,names:string[])=>String(val(r,names)??'').trim();
const yes=(v:any)=>['1','true','yes','بله','فعال','online','بلی'].includes(norm(v));
const num=(v:any)=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
async function rowsFromFile(file:File){
 const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});
 const ws=wb.Sheets[wb.SheetNames[0]];
 if(!ws)throw new Error('شیت قابل خواندن در فایل پیدا نشد');
 const rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:false}) as any[];
 if(!rows.length)throw new Error('فایل خالی است یا ردیف عنوان آن قابل تشخیص نیست');
 return rows;
}
export default function HotelSuperApp(){
 const [hotels,setHotels]=useState<HotelRow[]>([]); const [ops,setOps]=useState<Record<string,HotelAutomation & Workflow>>({});
 const [rules,setRules]=useState<ProviderRule[]>(DEFAULT_PROVIDER_RULES); const [tab,setTab]=useState('overview'); const [q,setQ]=useState('');
 const [provider,setProvider]=useState('all'); const [page,setPage]=useState(1); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const pageSize=60;
 useEffect(()=>{void loadAll()},[]);
 async function loadAll(){const db=getSupabase();if(!db){setMsg('Supabase تنظیم نشده است');return}setBusy(true);try{const [{data:h,error:he},{data:o,error:oe},{data:r}]=await Promise.all([db.from('ihos_hotels').select('*').limit(20000),db.from('ihos_hotel_automation').select('*').limit(20000),db.from('ihos_provider_rules').select('*').order('priority')]);if(he)throw he;if(oe)throw oe;if(h)setHotels(h as HotelRow[]);if(o){const m:any={};o.forEach((x:any)=>m[x.hotel_id]=({hotelId:x.hotel_id,hotelCode:x.hotel_code,provider:x.provider,hotelRate:x.hotel_rate,hotelCapacity:x.hotel_capacity,rateExpert:x.rate_expert,capacityExpert:x.capacity_expert,updatedAt:x.updated_at,onlineStatus:x.online_status,onlineOwner:x.online_owner,onlineBy:x.online_by,onlineAt:x.online_at,followUpOwner:x.follow_up_owner,followUpAt:x.follow_up_at,careOwner:x.care_owner,careStatus:x.care_status,careNextAt:x.care_next_at,notes:x.notes}));setOps(m)}if(r?.length)setRules(r.map((x:any)=>({name:x.name,rateApi:x.rate_api,capacityApi:x.capacity_api,active:x.active,effectiveFrom:x.effective_from,replacementProvider:x.replacement_provider,priority:x.priority})));setMsg(`${h?.length||0} هتل و ${o?.length||0} وضعیت عملیاتی بارگذاری شد`)}catch(e:any){setMsg(`خطای دریافت داده: ${e.message}`)}finally{setBusy(false)}}
 const enriched=useMemo(()=>hotels.map(h=>{const op=ops[h.id]||{hotelId:h.id,hotelCode:h.hotel_code,provider:h.provider||'IHO Provider',hotelRate:false,hotelCapacity:false};return {...h,...op,...evaluateAutomation({...op,provider:op.provider||h.provider||'IHO Provider'},rules)}}),[hotels,ops,rules]);
 const filtered=useMemo(()=>enriched.filter(h=>(provider==='all'||h.provider===provider)&&(!q||norm(`${h.title} ${h.hotel_code||''} ${h.city||''} ${h.province||''} ${h.rateExpert||''} ${h.capacityExpert||''}`).includes(norm(q)))),[enriched,provider,q]);
 const k=useMemo(()=>({all:enriched.length,online:enriched.filter(x=>x.fullyOnline).length,capacity:enriched.filter(x=>x.status==='ظرفیت آنلاین').length,expert:enriched.filter(x=>x.rateSource==='Expert'||x.capacitySource==='Expert').length,migrate:enriched.filter(x=>x.migrationNeeded).length,follow:enriched.filter(x=>x.followUpAt&&!['انجام شد','بسته شد'].includes(x.onlineStatus||'')).length}),[enriched]);
 const sourceRows=tab==='migration'?filtered.filter(x=>x.migrationNeeded):filtered;const pages=Math.max(1,Math.ceil(sourceRows.length/pageSize)); const rows=sourceRows.slice((page-1)*pageSize,page*pageSize);
 async function importHotels(file:File){setBusy(true);setMsg('در حال خواندن فایل هتل‌ها...');try{const data=await rowsFromFile(file);const mapped:HotelRow[]=data.map((r,i)=>{const code=text(r,['کد هتل','hotel_code','HotelCode','کدهتل']);return {id:code?`hotel-${code}`:`hotel-import-${Date.now()}-${i}`,hotel_code:code,title:text(r,['نام هتل','title','HotelName','نام']),country:text(r,['کشور']),province:text(r,['استان','province']),city:text(r,['شهر','city']),hotel_group:text(r,['گروه نوع هتل']),caring_category:text(r,['CaringCategory','caring_category']),hotel_type:text(r,['نوع هتل']),phone:text(r,['تلفن هتل']),reservation_phone:text(r,['تلن رزرواسیون','تلفن رزرواسیون']),capacity_total:num(val(r,['ظرفیت کلی هتل','ظرفیت','capacity_total'])),provider:text(r,['نام پروایدر','provider','Provider'])||'IHO Provider',pms:text(r,['PMS']),cooperation_status:text(r,['وضعیت همکاری','cooperation_status']),risk_status:text(r,['وضعیت ریسکی']),hotel_category:text(r,['دسته بندی هتل']),grade:text(r,['درجه هتل']),purchase_period:num(val(r,['دوره خرید'])),payment_period:num(val(r,['دوره پرداخت'])),status_end_date:text(r,['تاریخ پایان وضعیت']),status_start_date:text(r,['تاریخ شروع وضعیت']),contract_date:text(r,['تاریخ قرارداد']),site_visible:yes(val(r,['نمایش در سایت','site_visible'])),search_visible:yes(val(r,['نمایش در نتایج جستجو','search_visible']) )}}).filter(x=>x.title&&x.hotel_code);if(!mapped.length)throw new Error('هیچ ردیف معتبری پیدا نشد؛ ستون‌های «نام هتل» و «کد هتل» بررسی شوند');await upsertChunks('ihos_hotels',mapped);setHotels(mapped);setMsg(`✅ ${mapped.length} هتل از ${data.length} ردیف با موفقیت در Supabase سینک شد`)}catch(e:any){setMsg(`❌ ورود هتل‌ها ناموفق: ${e.message}`)}finally{setBusy(false)}}
 async function importExperts(file:File){setBusy(true);setMsg('در حال تطبیق فایل Assign Hotel...');try{const data=await rowsFromFile(file);const byCode=new Map(hotels.filter(h=>h.hotel_code).map(h=>[norm(h.hotel_code),h]));const byName=new Map<string,HotelRow[]>();hotels.forEach(h=>{const key=norm(h.title);byName.set(key,[...(byName.get(key)||[]),h])});const next={...ops};let matched=0,unmatched=0,ambiguous=0,empty=0;for(const r of data){const code=text(r,['کد هتل','hotel_code','HotelCode']);const hotelName=text(r,['نام هتل','HotelName','hotel_name']);const task=Number(val(r,['taskId','task id','task_id','TaskId']));const name=text(r,['First name','نام','کارشناس','expert_name','full_name']);if(!name||![1,2].includes(task)){empty++;continue}let h=code?byCode.get(norm(code)):undefined;if(!h&&hotelName){const candidates=byName.get(norm(hotelName))||[];if(candidates.length===1)h=candidates[0];else if(candidates.length>1){ambiguous++;continue}}if(!h){unmatched++;continue}const base:any=next[h.id]||{hotelId:h.id,hotelCode:h.hotel_code,provider:h.provider||'IHO Provider',hotelRate:false,hotelCapacity:false};if(task===2)base.rateExpert=name;if(task===1)base.capacityExpert=name;next[h.id]=base;matched++}const touched=Object.values(next).filter((x:any)=>x.rateExpert||x.capacityExpert).map((x:any)=>({id:x.hotelId,hotel_id:x.hotelId,hotel_code:x.hotelCode,provider:x.provider,hotel_rate:!!x.hotelRate,hotel_capacity:!!x.hotelCapacity,rate_expert:x.rateExpert||null,capacity_expert:x.capacityExpert||null,online_status:x.onlineStatus||'نیازمند بررسی',online_owner:x.onlineOwner||null,online_by:x.onlineBy||null,online_at:x.onlineAt||null,follow_up_owner:x.followUpOwner||null,follow_up_at:x.followUpAt||null,care_owner:x.careOwner||null,care_status:x.careStatus||'در صف Care',care_next_at:x.careNextAt||null,notes:x.notes||null,updated_at:new Date().toISOString()}));await upsertChunks('ihos_hotel_automation',touched);setOps(next);setMsg(`✅ ${matched} تخصیص ثبت شد | ${unmatched} نام پیدا نشد | ${ambiguous} نام تکراری | ${empty} ردیف بدون کارشناس/taskId`)}catch(e:any){setMsg(`❌ ورود کارشناسان ناموفق: ${e.message}`)}finally{setBusy(false)}}
 async function saveWorkflow(h:any){setBusy(true);try{const op:any=ops[h.id]||{hotelId:h.id,hotelCode:h.hotel_code,provider:h.provider||'IHO Provider',hotelRate:false,hotelCapacity:false};const row={id:h.id,hotel_id:h.id,hotel_code:h.hotel_code,provider:op.provider||h.provider||'IHO Provider',hotel_rate:!!op.hotelRate,hotel_capacity:!!op.hotelCapacity,rate_expert:op.rateExpert||null,capacity_expert:op.capacityExpert||null,online_status:op.onlineStatus||'نیازمند بررسی',online_owner:op.onlineOwner||null,online_by:op.onlineBy||null,online_at:op.onlineAt||null,follow_up_owner:op.followUpOwner||null,follow_up_at:op.followUpAt||null,care_owner:op.careOwner||null,care_status:op.careStatus||'در صف Care',care_next_at:op.careNextAt||null,notes:op.notes||null,updated_at:new Date().toISOString()};await upsertChunks('ihos_hotel_automation',[row]);setMsg(`وضعیت ${h.title} ذخیره شد`)}catch(e:any){setMsg(`خطای ذخیره: ${e.message}`)}finally{setBusy(false)}}
 function patch(id:string,p:Partial<HotelAutomation&Workflow>){setOps(s=>({...s,[id]:{...(s[id]||{hotelId:id,provider:hotels.find(h=>h.id===id)?.provider||'IHO Provider',hotelRate:false,hotelCapacity:false}),...p}}))}
 async function saveRules(){setBusy(true);try{const rs=rules.map(r=>({id:r.name.toLowerCase().replace(/\s+/g,'-'),name:r.name,rate_api:r.rateApi,capacity_api:r.capacityApi,active:r.active,effective_from:r.effectiveFrom||null,replacement_provider:r.replacementProvider||null,priority:r.priority,updated_at:new Date().toISOString()}));await upsertChunks('ihos_provider_rules',rs);setMsg('تنظیمات Provider ذخیره شد')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="superApp"><div className="superHead"><div><h2>سوپر اپ مدیریت هتل</h2><p>مدیریت کامل آنلاین‌سازی، مسئول اجرا، پیگیری و Care روی Supabase</p></div><div className="syncStatus"><Database size={16}/>{getSupabase()?'Supabase متصل':'حالت محلی'}{busy?' • در حال پردازش':''}</div></div>
 <div className="superTabs">{[['overview','نمای کل'],['hotels','وضعیت آنلاین'],['workflow','عملیات و پیگیری'],['migration','مهاجرت Provider'],['experts','کارشناسان'],['settings','تنظیمات و ورود داده']].map(([id,t])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setPage(1)}}>{t}</button>)}</div>
 {tab==='overview'&&<><div className="superKpis"><S icon={Hotel} t="کل هتل‌ها" v={k.all}/><S icon={CheckCircle2} t="۱۰۰٪ آنلاین" v={k.online}/><S icon={Activity} t="ظرفیت آنلاین" v={k.capacity}/><S icon={Users2} t="دخالت کارشناس" v={k.expert}/><S icon={ShieldAlert} t="نیازمند مهاجرت" v={k.migrate}/><S icon={ClipboardCheck} t="پیگیری باز" v={k.follow}/></div><div className="superGrid"><div className="superCard"><h3>ترکیب آنلاین‌سازی</h3>{['۱۰۰٪ آنلاین','ظرفیت آنلاین','نرخ آنلاین','کارشناس‌محور','آفلاین','نیازمند مهاجرت Provider'].map(s=>{const n=enriched.filter(x=>x.status===s).length;return <div className="metricRow" key={s}><span>{s}</span><i><b style={{width:`${enriched.length?n/enriched.length*100:0}%`}}/></i><strong>{n}</strong></div>})}</div><div className="superCard"><h3>اقدامات فوری</h3>{enriched.filter(x=>x.migrationNeeded||x.onlineStatus==='نیازمند بررسی').slice(0,10).map(x=><div className="actionMini" key={x.id}><div><b>{x.title}</b><small>{x.migrationNeeded?`${x.provider} ← ${x.suggestedProvider}`:(x.followUpOwner||'بدون مسئول')}</small></div><span>{x.score}%</span></div>)}</div></div></>}
 {(tab==='hotels'||tab==='migration')&&<><Filters q={q} setQ={setQ} provider={provider} setProvider={setProvider} enriched={enriched} setPage={setPage}/><div className="superTableWrap"><table className="superTable"><thead><tr><th>هتل</th><th>Provider</th><th>منبع نرخ</th><th>منبع ظرفیت</th><th>امتیاز</th><th>وضعیت</th><th>پیشنهاد</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.hotel_code||'—'} • {x.city||'—'} • {x.caring_category||'بدون Care'}</small></td><td>{x.provider}</td><td>{x.rateSource}</td><td>{x.capacitySource}</td><td><strong>{x.score}%</strong></td><td><span className={`statusPill ${x.fullyOnline?'ok':x.migrationNeeded?'bad':'warn'}`}>{x.status}</span></td><td>{x.migrationNeeded?`${x.suggestedProvider||'بررسی'} — ${x.reason}`:'—'}</td></tr>)}</tbody></table></div><Pager page={page} pages={pages} setPage={setPage}/></>}
 {tab==='workflow'&&<><Filters q={q} setQ={setQ} provider={provider} setProvider={setProvider} enriched={enriched} setPage={setPage}/><div className="superTableWrap"><table className="superTable workflowTable"><thead><tr><th>هتل</th><th>کارشناس نرخ / ظرفیت</th><th>وضعیت عملیات</th><th>مسئول آنلاین‌سازی</th><th>آنلاین‌کننده</th><th>پیگیری</th><th>Care</th><th>یادداشت</th><th></th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><b>{x.title}</b><small>{x.hotel_code} • {x.provider}</small></td><td><small>نرخ: {x.rateExpert||'—'}</small><small>ظرفیت: {x.capacityExpert||'—'}</small></td><td><select value={x.onlineStatus||'نیازمند بررسی'} onChange={e=>patch(x.id,{onlineStatus:e.target.value})}>{['نیازمند بررسی','در صف تماس','در حال مذاکره','پنل تحویل شد','در حال اتصال Provider','نرخ آنلاین شد','ظرفیت آنلاین شد','۱۰۰٪ آنلاین شد','عدم امکان آنلاین‌سازی','بسته شد'].map(v=><option key={v}>{v}</option>)}</select><input type="date" value={x.onlineAt||''} onChange={e=>patch(x.id,{onlineAt:e.target.value})}/></td><td><input value={x.onlineOwner||''} placeholder="چه کسی باید آنلاین کند؟" onChange={e=>patch(x.id,{onlineOwner:e.target.value})}/></td><td><input value={x.onlineBy||''} placeholder="چه کسی آنلاین کرد؟" onChange={e=>patch(x.id,{onlineBy:e.target.value})}/></td><td><input value={x.followUpOwner||''} placeholder="مسئول پیگیری" onChange={e=>patch(x.id,{followUpOwner:e.target.value})}/><input type="date" value={x.followUpAt||''} onChange={e=>patch(x.id,{followUpAt:e.target.value})}/></td><td><input value={x.careOwner||''} placeholder="مسئول Care" onChange={e=>patch(x.id,{careOwner:e.target.value})}/><select value={x.careStatus||'در صف Care'} onChange={e=>patch(x.id,{careStatus:e.target.value})}>{['در صف Care','در حال Care','Care انجام شد','نیازمند بازدید','نیازمند تماس مجدد','متوقف'].map(v=><option key={v}>{v}</option>)}</select><input type="date" value={x.careNextAt||''} onChange={e=>patch(x.id,{careNextAt:e.target.value})}/></td><td><textarea value={x.notes||''} onChange={e=>patch(x.id,{notes:e.target.value})}/></td><td><button className="iconBtn" onClick={()=>saveWorkflow(x)} title="ذخیره"><Save/></button></td></tr>)}</tbody></table></div><Pager page={page} pages={pages} setPage={setPage}/></>}
 {tab==='experts'&&<div className="superGrid">{Array.from(new Set(Object.values(ops).flatMap(x=>[x.rateExpert,x.capacityExpert,x.onlineOwner,x.followUpOwner,x.careOwner]).filter(Boolean))).map(name=>{const rs=Object.values(ops).filter(x=>x.rateExpert===name).length,cs=Object.values(ops).filter(x=>x.capacityExpert===name).length,fo=Object.values(ops).filter(x=>x.followUpOwner===name).length,care=Object.values(ops).filter(x=>x.careOwner===name).length;return <div className="superCard expertCard" key={name as string}><Users2/><h3>{name}</h3><p>{rs} نرخ • {cs} ظرفیت • {fo} پیگیری • {care} Care</p><div className="metricRow"><span>بار کاری</span><i><b style={{width:`${Math.min(100,(rs+cs+fo+care)/5)}%`}}/></i><strong>{rs+cs+fo+care}</strong></div></div>})}</div>}
 {tab==='settings'&&<div className="settingsGrid"><div className="superCard"><h3><CloudUpload/> ورود و سینک داده</h3><Upload label="All hotels.xlsx" hint="نام هتل + کد هتل + نام پروایدر + ظرفیت کلی هتل" onFile={importHotels}/><Upload label="assignment hotel.xlsx" hint="نام هتل + taskId + First name؛ اتصال با نام هتل" onFile={importExperts}/><div className="importMsg">{msg||'فایل را انتخاب کن؛ نتیجه تطبیق کامل نمایش داده می‌شود.'}</div><button className="btn ghost" onClick={loadAll}><RefreshCcw/> بارگذاری مجدد از Supabase</button></div><div className="superCard"><h3><Settings2/> Provider Matrix</h3>{rules.map((r,i)=><div className="ruleRow" key={`${r.name}-${i}`}><input value={r.name} onChange={e=>setRules(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><label><input type="checkbox" checked={r.rateApi} onChange={e=>setRules(a=>a.map((x,j)=>j===i?{...x,rateApi:e.target.checked}:x))}/> نرخ API</label><label><input type="checkbox" checked={r.capacityApi} onChange={e=>setRules(a=>a.map((x,j)=>j===i?{...x,capacityApi:e.target.checked}:x))}/> ظرفیت API</label><input type="date" value={r.effectiveFrom||''} onChange={e=>setRules(a=>a.map((x,j)=>j===i?{...x,effectiveFrom:e.target.value}:x))}/><input placeholder="Provider پیشنهادی" value={r.replacementProvider||''} onChange={e=>setRules(a=>a.map((x,j)=>j===i?{...x,replacementProvider:e.target.value}:x))}/></div>)}<button className="btn primary" onClick={saveRules}><RefreshCcw/> ذخیره در Supabase</button></div></div>}
 </div>
}
function Filters({q,setQ,provider,setProvider,enriched,setPage}:any){return <div className="filterBar"><Filter size={16}/><input placeholder="جستجوی نام، کد، شهر یا کارشناس..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={provider} onChange={e=>{setProvider(e.target.value);setPage(1)}}><option value="all">همه Providerها</option>{[...new Set(enriched.map((x:any)=>x.provider).filter(Boolean))].map((x:any)=><option key={x}>{x}</option>)}</select></div>}
function Pager({page,pages,setPage}:any){return <div className="pager"><button disabled={page<=1} onClick={()=>setPage((p:number)=>p-1)}>قبلی</button><span>{page} از {pages}</span><button disabled={page>=pages} onClick={()=>setPage((p:number)=>p+1)}>بعدی</button></div>}
function S({icon:Icon,t,v}:any){return <div className="superKpi"><Icon/><div><span>{t}</span><strong>{Number(v||0).toLocaleString('fa-IR')}</strong></div></div>}
function Upload({label,hint,onFile}:any){return <label className="uploadBox"><CloudUpload/><span>{label}</span><small>{hint}</small><input type="file" accept=".xlsx,.xls,.csv" onClick={(e:any)=>{e.currentTarget.value=''}} onChange={e=>{const f=e.target.files?.[0];if(f)void onFile(f)}}/></label>}
