'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,CheckCircle2,CloudUpload,Database,Filter,Hotel,RefreshCcw,Settings2,ShieldAlert,Users2,Save,Trash2,ArchiveRestore,LockKeyhole} from 'lucide-react';
import * as XLSX from 'xlsx';
import {DEFAULT_PROVIDER_RULES} from '@/lib/superapp/automation';
import type {ProviderRule} from '@/lib/superapp/types';
import {getSupabase,upsertChunks} from '@/lib/superapp/supabase';

type Row={id:string;hotel_code?:string;title:string;city?:string;province?:string;caring_category?:string;cooperation_status?:string;provider?:string;hotel_rate?:boolean;hotel_capacity?:boolean;rate_expert?:string;capacity_expert?:string;rate_api?:boolean;capacity_api?:boolean;rate_online?:boolean;capacity_online?:boolean;automation_score?:number;automation_status?:string;migration_needed?:boolean;replacement_provider?:string;online_status?:string;follow_up_owner?:string;follow_up_at?:string;care_owner?:string;care_status?:string;care_next_at?:string;notes?:string};
type Stats={all:number;online:number;capacity:number;rate:number;expert:number;offline:number;migrate:number};
const emptyStats:Stats={all:0,online:0,capacity:0,rate:0,expert:0,offline:0,migrate:0};
const norm=(v:any)=>String(v??'').replace(/\u200c/g,' ').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim().toLowerCase();
const val=(r:any,names:string[])=>{for(const k of Object.keys(r)){if(names.some(n=>norm(n)===norm(k))&&String(r[k]??'').trim()!=='')return r[k]}return undefined};
const text=(r:any,names:string[])=>String(val(r,names)??'').trim();
const yes=(v:any)=>['1','true','yes','بله','فعال','online','بلی'].includes(norm(v));
const num=(v:any)=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
async function rowsFromFile(file:File){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('شیت قابل خواندن پیدا نشد');const rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:false}) as any[];if(!rows.length)throw new Error('فایل خالی است');return rows}

export default function HotelSuperApp({isSuperAdmin=false,actor}:{isSuperAdmin?:boolean;actor?:{id?:string;username?:string;name?:string}}){
 const [rows,setRows]=useState<Row[]>([]),[rules,setRules]=useState<ProviderRule[]>(DEFAULT_PROVIDER_RULES),[stats,setStats]=useState<Stats>(emptyStats);
 const [tab,setTab]=useState('overview'),[q,setQ]=useState(''),[provider,setProvider]=useState('all'),[status,setStatus]=useState('all');
 const [page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const debounce=useRef<any>(null); const pageSize=50;
 useEffect(()=>{void loadRules();void loadStats()},[]);
 useEffect(()=>{clearTimeout(debounce.current);debounce.current=setTimeout(()=>void loadPage(),250);return()=>clearTimeout(debounce.current)},[page,q,provider,status,tab]);
 async function loadRules(){const db=getSupabase();if(!db)return;const {data}=await db.from('ihos_provider_rules').select('*').order('priority');if(data?.length)setRules(data.map((x:any)=>({name:x.name,rateApi:x.rate_api,capacityApi:x.capacity_api,active:x.active,effectiveFrom:x.effective_from,replacementProvider:x.replacement_provider,priority:x.priority})))}
 async function loadStats(){const db=getSupabase();if(!db)return;const {data,error}=await db.rpc('ihos_hotel_dashboard_stats');if(!error&&data)setStats(data as Stats)}
 async function loadPage(){const db=getSupabase();if(!db){setMsg('Supabase تنظیم نشده است');return}setBusy(true);try{let query:any=db.from('ihos_hotel_status_v').select('*',{count:'exact'});if(provider!=='all')query=query.eq('provider',provider);if(status!=='all')query=query.eq('automation_status',status);if(tab==='migration')query=query.eq('migration_needed',true);if(q.trim()){const s=q.trim().replace(/[%_,]/g,' ');query=query.or(`title.ilike.%${s}%,hotel_code.ilike.%${s}%,city.ilike.%${s}%,province.ilike.%${s}%,rate_expert.ilike.%${s}%,capacity_expert.ilike.%${s}%`)}const from=(page-1)*pageSize;const {data,error,count}=await query.order('title',{ascending:true}).range(from,from+pageSize-1);if(error)throw error;setRows((data||[]) as Row[]);setTotal(count||0);setMsg(`${(count||0).toLocaleString('fa-IR')} نتیجه`)}catch(e:any){setMsg(`خطای دریافت: ${e.message}. فایل SUPABASE-PERFORMANCE-V6.sql را اجرا کن.`)}finally{setBusy(false)}}
 async function refresh(){await Promise.all([loadStats(),loadPage(),loadRules()])}
 async function importHotels(file:File){setBusy(true);setMsg('در حال پردازش فایل هتل‌ها...');try{const data=await rowsFromFile(file);const now=Date.now();const mapped=data.map((r,i)=>{const code=text(r,['کد هتل','hotel_code','HotelCode','کدهتل']);return {id:code?`hotel-${code}`:`hotel-import-${now}-${i}`,hotel_code:code,title:text(r,['نام هتل','title','HotelName','نام']),country:text(r,['کشور']),province:text(r,['استان','province']),city:text(r,['شهر','city']),hotel_group:text(r,['گروه نوع هتل']),caring_category:text(r,['CaringCategory','caring_category']),hotel_type:text(r,['نوع هتل']),phone:text(r,['تلفن هتل']),reservation_phone:text(r,['تلفن رزرواسیون','تلن رزرواسیون']),capacity_total:num(val(r,['ظرفیت کلی هتل','ظرفیت','capacity_total'])),provider:text(r,['نام پروایدر','provider','Provider'])||'IHO Provider',pms:text(r,['PMS']),cooperation_status:text(r,['وضعیت همکاری','cooperation_status']),risk_status:text(r,['وضعیت ریسکی']),hotel_category:text(r,['دسته بندی هتل']),grade:text(r,['درجه هتل']),purchase_period:num(val(r,['دوره خرید'])),payment_period:num(val(r,['دوره پرداخت'])),status_end_date:text(r,['تاریخ پایان وضعیت']),status_start_date:text(r,['تاریخ شروع وضعیت']),contract_date:text(r,['تاریخ قرارداد']),site_visible:yes(val(r,['نمایش در سایت','site_visible'])),search_visible:yes(val(r,['نمایش در نتایج جستجو','search_visible']))}}).filter(x=>x.title&&x.hotel_code);if(!mapped.length)throw new Error('ستون نام هتل یا کد هتل شناسایی نشد');await upsertChunks('ihos_hotels',mapped,300);setMsg(`✅ ${mapped.length.toLocaleString('fa-IR')} هتل ذخیره شد`);setPage(1);await refresh()}catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}}
 async function importExperts(file:File){setBusy(true);setMsg('در حال تطبیق تخصیص کارشناسان...');try{const data=await rowsFromFile(file);const db=getSupabase();if(!db)throw new Error('Supabase تنظیم نشده');const all:any[]=[];for(let from=0;;from+=1000){const {data:h,error}=await db.from('ihos_hotels').select('id,hotel_code,title,provider').range(from,from+999);if(error)throw error;all.push(...(h||[]));if(!h||h.length<1000)break}const byCode=new Map(all.filter(x=>x.hotel_code).map(x=>[norm(x.hotel_code),x]));const byName=new Map<string,any[]>();all.forEach(h=>byName.set(norm(h.title),[...(byName.get(norm(h.title))||[]),h]));const patch=new Map<string,any>();let matched=0,unmatched=0;for(const r of data){const code=text(r,['کد هتل','hotel_code','HotelCode']);const hotelName=text(r,['نام هتل','HotelName','hotel_name']);const task=Number(val(r,['taskId','task id','task_id','TaskId']));const name=text(r,['First name','نام','کارشناس','expert_name','full_name']);if(!name||![1,2].includes(task))continue;let h=code?byCode.get(norm(code)):undefined;if(!h&&hotelName){const c=byName.get(norm(hotelName))||[];if(c.length===1)h=c[0]}if(!h){unmatched++;continue}const old=patch.get(h.id)||{id:h.id,hotel_id:h.id,hotel_code:h.hotel_code,provider:h.provider||'IHO Provider',hotel_rate:false,hotel_capacity:false,updated_at:new Date().toISOString()};if(task===1)old.capacity_expert=name;else old.rate_expert=name;patch.set(h.id,old);matched++}await upsertChunks('ihos_hotel_automation',[...patch.values()],300);setMsg(`✅ ${matched.toLocaleString('fa-IR')} تخصیص ثبت شد؛ ${unmatched.toLocaleString('fa-IR')} مورد تطبیق نشد`);await refresh()}catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}}

 async function destructiveAction(action:'delete-row'|'clear-table',table:string,id?:string,label?:string){
  if(!isSuperAdmin){setMsg('فقط سوپر ادمین مجاز به حذف اطلاعات است');return}
  const phrase=action==='clear-table'?`حذف ${label||table}`:'حذف';
  const typed=window.prompt(`برای تایید عبارت «${phrase}» را دقیق وارد کنید`);
  if(typed!==phrase){setMsg('عملیات حذف لغو شد؛ عبارت تایید صحیح نبود');return}
  const key=window.prompt('رمز حذف سوپر ادمین را وارد کنید'); if(!key)return;
  setBusy(true);setMsg('در حال ثبت نسخه پشتیبان و حذف اطلاعات...');
  try{
   const res=await fetch('/api/admin/delete',{method:'DELETE',headers:{'Content-Type':'application/json','x-delete-key':key},body:JSON.stringify({action,table,id,actor})});
   const out=await res.json(); if(!res.ok)throw new Error(out.error||'عملیات حذف ناموفق بود');
   setMsg(`✅ ${out.deleted||1} رکورد حذف و در سطل بازیافت ثبت شد`); await refresh();
  }catch(e:any){setMsg(`❌ ${e.message}`)}finally{setBusy(false)}
 }

 async function saveRules(){setBusy(true);try{await upsertChunks('ihos_provider_rules',rules.map(r=>({id:norm(r.name).replace(/\s+/g,'-'),name:r.name,rate_api:r.rateApi,capacity_api:r.capacityApi,active:r.active,effective_from:r.effectiveFrom||null,replacement_provider:r.replacementProvider||null,priority:r.priority,updated_at:new Date().toISOString()})),50);setMsg('قوانین Provider ذخیره شد');await refresh()}catch(e:any){setMsg(`خطا: ${e.message}`)}finally{setBusy(false)}}
 const providers=useMemo(()=>['all',...rules.map(r=>r.name)], [rules]);const pages=Math.max(1,Math.ceil(total/pageSize));
 return <div className="superAppShell">
  <div className="superHero"><div><h1>سوپر اپ مدیریت هتل</h1><p>نسخه سریع: صفحه‌بندی و محاسبات کاملاً سمت Supabase</p></div><button className="btn ghost" onClick={refresh} disabled={busy}><RefreshCcw size={17}/>{busy?'در حال دریافت...':'به‌روزرسانی'}</button></div>
  <div className="superKpis">{[[Hotel,'کل هتل‌ها',stats.all],[CheckCircle2,'۱۰۰٪ آنلاین',stats.online],[Activity,'ظرفیت آنلاین',stats.capacity],[Users2,'کارشناس‌محور',stats.expert],[ShieldAlert,'نیازمند مهاجرت',stats.migrate]].map(([Icon,label,value]:any)=><div className="superKpi" key={label}><Icon/><div><b>{Number(value).toLocaleString('fa-IR')}</b><span>{label}</span></div></div>)}</div>
  <div className="superTabs">{[['overview','وضعیت هتل‌ها'],['migration','پیشنهاد مهاجرت'],['import','ورود داده'],['settings','تنظیمات Provider'],...(isSuperAdmin?[['data','مدیریت و حذف اطلاعات']]:[])].map(x=><button className={tab===x[0]?'active':''} onClick={()=>{setTab(x[0]);setPage(1)}} key={x[0]}>{x[1]}</button>)}</div>
  {msg&&<div className="superMsg">{msg}</div>}
  {(tab==='overview'||tab==='migration')&&<><div className="superFilters"><div className="searchBox"><Filter size={16}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="نام، کد، شهر یا کارشناس..."/></div><select value={provider} onChange={e=>{setProvider(e.target.value);setPage(1)}}>{providers.map(x=><option key={x} value={x}>{x==='all'?'همه Providerها':x}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">همه وضعیت‌ها</option>{['۱۰۰٪ آنلاین','ظرفیت آنلاین','نرخ آنلاین','کارشناس‌محور','آفلاین','نیازمند مهاجرت Provider'].map(x=><option key={x}>{x}</option>)}</select></div><div className="superTableWrap"><table className="superTable"><thead><tr><th>هتل</th><th>Provider</th><th>نرخ</th><th>ظرفیت</th><th>امتیاز</th><th>وضعیت</th><th>پیشنهاد</th>{isSuperAdmin&&<th>حذف</th>}</tr></thead><tbody>{busy&&!rows.length?<tr><td colSpan={7}>در حال بارگذاری...</td></tr>:rows.map(h=><tr key={h.id}><td><b>{h.title}</b><small>{h.hotel_code} · {h.city||h.province||'—'}</small></td><td>{h.provider}</td><td>{h.rate_api?'API':h.hotel_rate?'هتل':h.rate_expert||'آفلاین'}</td><td>{h.capacity_api?'API':h.hotel_capacity?'هتل':h.capacity_expert||'آفلاین'}</td><td><b>{h.automation_score||0}%</b></td><td><span className={`statusPill ${h.automation_score===100?'ok':h.migration_needed?'danger':'warn'}`}>{h.automation_status}</span></td><td>{h.migration_needed?(h.replacement_provider||'Lamasoo'):'—'}</td>{isSuperAdmin&&<td><button className="iconBtn dangerBtn" title="حذف هتل" onClick={()=>destructiveAction('delete-row','ihos_hotels',h.id,h.title)}><Trash2 size={16}/></button></td>}</tr>)}</tbody></table></div><div className="pager"><button disabled={page<=1||busy} onClick={()=>setPage(p=>p-1)}>قبلی</button><span>صفحه {page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span><button disabled={page>=pages||busy} onClick={()=>setPage(p=>p+1)}>بعدی</button></div></>}
  {tab==='import'&&<div className="importGrid"><label className="uploadCard"><CloudUpload/><b>فایل BI هتل‌ها</b><span>xlsx / xls / csv</span><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&importHotels(e.target.files[0])}/></label><label className="uploadCard"><Users2/><b>فایل تخصیص کارشناسان</b><span>taskId 1 ظرفیت، taskId 2 نرخ</span><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&importExperts(e.target.files[0])}/></label><div className="infoCard"><Database/><b>Import بهینه</b><p>ذخیره دسته‌ای ۳۰۰تایی و بدون قرار دادن ۹۱۵۴ ردیف در حافظه رابط کاربری.</p></div></div>}
  {tab==='settings'&&<div className="rulesPanel"><div className="rulesHeader"><div><Settings2/><b>Provider Matrix</b></div><button className="btn primary" onClick={saveRules} disabled={busy}><Save size={16}/>ذخیره</button></div>{rules.map((r,i)=><div className="ruleRow" key={r.name}><input value={r.name} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><label><input type="checkbox" checked={r.rateApi} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,rateApi:e.target.checked}:x))}/>API نرخ</label><label><input type="checkbox" checked={r.capacityApi} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,capacityApi:e.target.checked}:x))}/>API ظرفیت</label><label><input type="checkbox" checked={r.active} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,active:e.target.checked}:x))}/>فعال</label><input type="date" value={r.effectiveFrom||''} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,effectiveFrom:e.target.value}:x))}/><input placeholder="Provider پیشنهادی" value={r.replacementProvider||''} onChange={e=>setRules(rs=>rs.map((x,j)=>j===i?{...x,replacementProvider:e.target.value}:x))}/></div>)}</div>}

  {tab==='data'&&isSuperAdmin&&<div className="dataGovernance">
   <div className="governanceHero"><div><LockKeyhole/><div><h3>مرکز مدیریت و حذف اطلاعات</h3><p>تمام حذف‌ها فقط با رمز سوپر ادمین، تایید عبارتی و ثبت نسخه در سطل بازیافت انجام می‌شوند.</p></div></div><span className="statusPill danger">Super Admin Only</span></div>
   <div className="dangerGrid">
    {[
     ['ihos_hotel_automation','وضعیت نرخ، ظرفیت و تخصیص کارشناسان','پاک‌سازی داده‌های اتوماسیون هتل‌ها'],
     ['ihos_provider_rules','قوانین Provider','پاک‌سازی Provider Matrix'],
     ['ihos_hotels','همه هتل‌ها','حذف کامل دیتای هتل‌ها و وابستگی‌های اتوماسیون'],
     ['ihos_tasks','همه تسک‌ها','پاک‌سازی Task Manager'],
     ['ihos_task_activities','فعالیت‌های تسک','پاک‌سازی فعالیت‌ها و چک‌لیست‌ها'],
     ['ihos_documents','اسناد','پاک‌سازی متادیتای اسناد'],
     ['ihos_calendar_events','رویدادهای تقویم','پاک‌سازی تقویم'],
     ['ihos_notifications','اعلان‌ها','پاک‌سازی اعلان‌ها'],
     ['ihos_reminders','یادآورها','پاک‌سازی یادآورها'],
     ['ihos_goals','اهداف','پاک‌سازی اهداف'],
     ['ihos_projects','پروژه‌ها','پاک‌سازی پروژه‌ها'],
     ['ihos_activity_logs','لاگ‌های عملیاتی','پاک‌سازی لاگ‌های عمومی؛ لاگ حذف امن باقی می‌ماند']
    ].map(([table,label,desc])=><article className="dangerCard" key={table}><div><ArchiveRestore/><h4>{label}</h4><p>{desc}</p></div><button className="btn danger" disabled={busy} onClick={()=>destructiveAction('clear-table',table,undefined,label)}><Trash2 size={16}/> حذف اطلاعات</button></article>)}
   </div>
   <div className="governanceNote"><ShieldAlert/><div><b>حفاظت از کاربران و تنظیمات</b><p>حذف گروهی کاربران، نقش‌ها و تنظیمات از رابط کاربری مسدود است تا دسترسی سیستم از بین نرود. حذف تکی آن‌ها نیز فقط توسط سوپر ادمین انجام می‌شود.</p></div></div>
  </div>}

 </div>
}
