'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { BarChart3, Bell, Building2, CalendarDays, CheckCircle2, ClipboardList, FileText, Hotel, LayoutDashboard, Lock, MessageSquare, Plus, Search, Settings, ShieldCheck, Sparkles, Target, Users, Zap } from 'lucide-react';

type Role='admin'|'city_manager'|'expert'|'panel'|'content'|'finance';
type Member={id:string;name:string;role:Role;zone:string;position:string;password:string;active:boolean;score:number};
type HotelT={id:string;name:string;city:string;province:string;grade:string;status:string;owner:string;priority:'A'|'B'|'C'|'D';rooms:number;provider:string;lastFollow:string};
type Task={id:string;title:string;description:string;hotel:string;city:string;category:string;priority:'فوری'|'بالا'|'متوسط'|'پایین';status:string;assignedTo:string;due:string;createdAt:string;comments:string[]};
const roles:Record<Role,string>={admin:'مدیر سیستم',city_manager:'سیتی‌منیجر',expert:'کارشناس تامین',panel:'تیم پنل',content:'محتوا',finance:'مالی'};
const statuses=['جدید','در حال پیگیری','منتظر پاسخ','نیازمند اصلاح','انجام‌شده'];
const cats=['ظرفیت','قیمت','قرارداد','پنل','محتوا','مالی','همکاری'];
const seedMembers:Member[]=[
{id:'u-admin',name:'محمدباقر ذوالفقاری',role:'admin',zone:'همه زون‌ها',position:'مدیر زنجیره تامین',password:'123456',active:true,score:98},
{id:'u-1',name:'محـدثه باقری',role:'city_manager',zone:'مرکز',position:'سیتی‌منیجر مرکز',password:'123456',active:true,score:89},
{id:'u-2',name:'نرگس قدرتی',role:'city_manager',zone:'شرق و جنوب',position:'سیتی‌منیجر شرق و جنوب',password:'123456',active:true,score:86},
{id:'u-3',name:'سپیده دولت‌آبادی',role:'city_manager',zone:'شمال و غرب',position:'سیتی‌منیجر شمال و غرب',password:'123456',active:true,score:84},
{id:'u-4',name:'فائزه سالاری',role:'expert',zone:'مرکز',position:'کارشناس نرخ و ظرفیت',password:'123456',active:true,score:77},
{id:'u-5',name:'پگاه واعظین',role:'expert',zone:'شمال و غرب',position:'کارشناس نرخ و ظرفیت',password:'123456',active:true,score:74},
{id:'u-6',name:'مهلا بهرامی‌زاده',role:'expert',zone:'کنترل ظرفیت',position:'کارشناس ظرفیت',password:'123456',active:true,score:72},
{id:'u-7',name:'منصوره یکتایی',role:'panel',zone:'پنل',position:'لید پنل',password:'123456',active:true,score:88}
];
const seedHotels:HotelT[]=[
{id:'h1',name:'هتل درویشی',city:'مشهد',province:'خراسان رضوی',grade:'5 ستاره',status:'لایو',owner:'فائزه سالاری',priority:'A',rooms:223,provider:'Direct',lastFollow:'امروز'},
{id:'h2',name:'هتل پارس',city:'مشهد',province:'خراسان رضوی',grade:'5 ستاره',status:'نیازمند ظرفیت',owner:'مهلا بهرامی‌زاده',priority:'A',rooms:190,provider:'Direct',lastFollow:'دیروز'},
{id:'h3',name:'هتل اسپیناس پالاس',city:'تهران',province:'تهران',grade:'5 ستاره',status:'لایو',owner:'پگاه واعظین',priority:'A',rooms:400,provider:'Direct',lastFollow:'۳ روز قبل'},
{id:'h4',name:'هتل ترنج',city:'کیش',province:'هرمزگان',grade:'5 ستاره',status:'در حال مذاکره',owner:'نرگس قدرتی',priority:'B',rooms:100,provider:'Partner',lastFollow:'امروز'},
{id:'h5',name:'هتل عباسی',city:'اصفهان',province:'اصفهان',grade:'5 ستاره',status:'قرارداد',owner:'محدثه باقری',priority:'A',rooms:225,provider:'Direct',lastFollow:'هفته قبل'}
];
const seedTasks:Task[]=[
{id:'t1',title:'دریافت ظرفیت آخر هفته',description:'برای پیک آخر هفته ظرفیت اتاق‌های دبل و توئین گرفته شود.',hotel:'هتل درویشی',city:'مشهد',category:'ظرفیت',priority:'فوری',status:'در حال پیگیری',assignedTo:'فائزه سالاری',due:'امروز',createdAt:'امروز',comments:['تماس اول انجام شد.']},
{id:'t2',title:'اصلاح قیمت نسبت به رقبا',description:'قیمت سایت با تامین‌کننده و رقبا اختلاف دارد.',hotel:'هتل اسپیناس پالاس',city:'تهران',category:'قیمت',priority:'بالا',status:'جدید',assignedTo:'پگاه واعظین',due:'فردا',createdAt:'امروز',comments:[]},
{id:'t3',title:'پیگیری تمدید قرارداد',description:'قرارداد هتل عباسی نیازمند تمدید است.',hotel:'هتل عباسی',city:'اصفهان',category:'قرارداد',priority:'بالا',status:'منتظر پاسخ',assignedTo:'محدثه باقری',due:'۲ روز دیگر',createdAt:'دیروز',comments:['قرارداد برای هتل ارسال شد.']},
{id:'t4',title:'دریافت عکس جدید',description:'عکس‌های اتاق‌ها قدیمی هستند.',hotel:'هتل ترنج',city:'کیش',category:'محتوا',priority:'متوسط',status:'نیازمند اصلاح',assignedTo:'منصوره یکتایی',due:'این هفته',createdAt:'امروز',comments:[]},
{id:'t5',title:'تست ورود پنل هتل',description:'هتل اعلام کرده ورود به پنل مشکل دارد.',hotel:'هتل پارس',city:'مشهد',category:'پنل',priority:'فوری',status:'انجام‌شده',assignedTo:'منصوره یکتایی',due:'امروز',createdAt:'امروز',comments:['حل شد.']}
];
function load<T>(k:string,d:T){ if(typeof window==='undefined')return d; try{return JSON.parse(localStorage.getItem(k)||'')||d}catch{return d} }
function save(k:string,v:any){ if(typeof window!=='undefined')localStorage.setItem(k,JSON.stringify(v)) }
async function sbGet(table:string){ if(!supabase)return null; const {data,error}=await supabase.from(table).select('*'); if(error)return null; return data; }
async function sbUpsert(table:string,rows:any[]){ if(!supabase)return false; const {error}=await supabase.from(table).upsert(rows); return !error; }
function mapMemberIn(r:any):Member{return {id:r.id,name:r.name,role:r.role,zone:r.zone,position:r.position,password:r.password||'123456',active:r.active!==false,score:r.score||70}}
function mapTaskIn(r:any):Task{return {id:r.id,title:r.title,description:r.description||'',hotel:r.hotel,city:r.city,category:r.category,priority:r.priority,status:r.status,assignedTo:r.assigned_to||r.assignedTo,due:r.due,createdAt:r.created_at_label||r.createdAt||'امروز',comments:r.comments||[]}}

export default function Page(){
 const [members,setMembers]=useState<Member[]>(seedMembers),[hotels,setHotels]=useState<HotelT[]>(seedHotels),[tasks,setTasks]=useState<Task[]>(seedTasks);
 const [user,setUser]=useState<Member|null>(null),[loginUser,setLoginUser]=useState('u-admin'),[pass,setPass]=useState(''),[tab,setTab]=useState('dashboard'),[q,setQ]=useState(''),[online,setOnline]=useState(false);
 const [draft,setDraft]=useState({title:'',hotel:'هتل درویشی',category:'ظرفیت',priority:'متوسط' as Task['priority'],assignedTo:'فائزه سالاری',due:'امروز',description:''});
 const [newMember,setNewMember]=useState({name:'',role:'expert' as Role,zone:'مرکز',position:'کارشناس تامین',password:'123456'});
 useEffect(()=>{(async()=>{ const lm=load('iho_os_members',seedMembers), lh=load('iho_os_hotels',seedHotels), lt=load('iho_os_tasks',seedTasks); setMembers(lm);setHotels(lh);setTasks(lt); const sm=await sbGet('iho_os_members'); const st=await sbGet('iho_os_tasks'); const sh=await sbGet('iho_os_hotels'); if(sm&&st){setOnline(true); if(sm.length)setMembers(sm.map(mapMemberIn)); if(st.length)setTasks(st.map(mapTaskIn)); if(sh&&sh.length)setHotels(sh as any); if(!sm.length) await sbUpsert('iho_os_members', seedMembers as any); if(!st.length) await sbUpsert('iho_os_tasks', seedTasks.map(t=>({...t,assigned_to:t.assignedTo,created_at_label:t.createdAt})) as any); if(sh&&!sh.length) await sbUpsert('iho_os_hotels', seedHotels as any); } })()},[]);
 useEffect(()=>save('iho_os_members',members),[members]); useEffect(()=>save('iho_os_tasks',tasks),[tasks]); useEffect(()=>save('iho_os_hotels',hotels),[hotels]);
 async function persistMembers(v:Member[]){setMembers(v); await sbUpsert('iho_os_members',v as any)}
 async function persistTasks(v:Task[]){setTasks(v); await sbUpsert('iho_os_tasks',v.map(t=>({...t,assigned_to:t.assignedTo,created_at_label:t.createdAt})) as any)}
 function login(){const u=members.find(m=>m.id===loginUser&&m.active); if(!u)return alert('کاربر فعال نیست'); if(u.password!==pass)return alert('رمز عبور اشتباه است'); setUser(u)}
 function addTask(){ if(!draft.title)return; const hotel=hotels.find(h=>h.name===draft.hotel); const t:Task={id:'t-'+Date.now(),title:draft.title,description:draft.description,hotel:draft.hotel,city:hotel?.city||'',category:draft.category,priority:draft.priority,status:'جدید',assignedTo:draft.assignedTo,due:draft.due,createdAt:'امروز',comments:[]}; persistTasks([t,...tasks]); setDraft({...draft,title:'',description:''}) }
 function moveTask(id:string,status:string){persistTasks(tasks.map(t=>t.id===id?{...t,status}:t))}
 function addMember(){ if(!newMember.name)return; const m:Member={id:'u-'+Date.now(),...newMember,active:true,score:70}; persistMembers([m,...members]); setNewMember({name:'',role:'expert',zone:'مرکز',position:'کارشناس تامین',password:'123456'})}
 function disableMember(id:string){persistMembers(members.map(m=>m.id===id?{...m,active:false}:m))}
 const visibleTasks=useMemo(()=> user?.role==='admin'?tasks:tasks.filter(t=>t.assignedTo===user?.name),[tasks,user]);
 const filteredTasks=visibleTasks.filter(t=>(t.title+t.hotel+t.city+t.assignedTo+t.category).includes(q));
 const kpi={open:tasks.filter(t=>t.status!=='انجام‌شده').length,done:tasks.filter(t=>t.status==='انجام‌شده').length,urgent:tasks.filter(t=>t.priority==='فوری').length,team:members.filter(m=>m.active).length};
 if(!user) return <div className="login"><div className="loginbox"><div className="loginhero"><div className="logo">OS</div><h1>IranHotel Operations System</h1><p>سیستم عملیاتی تیم تأمین، CRM هتل‌ها، مدیریت تسک، KPI، تیم و گزارش‌های مدیریتی.</p><div style={{height:22}}/><span className="pill ok">Supabase: {online?'Online':'Local/Demo'}</span></div><div className="loginform"><h2>ورود به پنل سازمانی</h2><p className="label">هر کاربر با نام و رمز خودش وارد می‌شود.</p><select value={loginUser} onChange={e=>setLoginUser(e.target.value)}>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name} — {roles[m.role]}</option>)}</select><input type="password" placeholder="رمز عبور" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')login()}}/><button className="btn brand" onClick={login}>ورود امن</button><p className="label">رمز اولیه نسخه تست: 123456</p></div></div></div>;
 const nav=[['dashboard','داشبورد',LayoutDashboard],['tasks','Task Center',ClipboardList],['hotels','Hotel CRM',Hotel],['team','تیم و دسترسی',Users],['reports','گزارش‌ها',BarChart3],['calendar','تقویم و پیگیری',CalendarDays],['docs','قرارداد و اسناد',FileText],['settings','تنظیمات',Settings]] as any[];
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">IHO</div><div><h1>IranHotel OS</h1><p>Operations Command Center</p></div></div><div className="nav">{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span></button>)}</div><div style={{marginTop:24}} className="card"><span className={online?'pill ok':'pill warn'}>{online?'Online Supabase':'Local Mode'}</span><p className="label">ورود: {user.name}</p></div></aside><main className="main"><div className="topbar"><input className="search" placeholder="جستجوی هتل، تسک، کارشناس، شهر..." value={q} onChange={e=>setQ(e.target.value)}/><div style={{display:'flex',gap:10,alignItems:'center'}}><button className="btn secondary"><Bell size={16}/> اعلان‌ها</button><div className="userchip"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><div className="label">{roles[user.role]}</div></div></div></div></div>
 {tab==='dashboard'&&<><div className="section"><div><h2>داشبورد فرماندهی عملیات</h2><p className="label">نمای کلی عملکرد تأمین، هتل‌ها، تسک‌ها و تیم</p></div><button className="btn brand" onClick={()=>setTab('tasks')}><Plus size={16}/> تسک جدید</button></div><div className="grid kpi"><Kpi icon={<ClipboardList/>} title="تسک‌های باز" value={kpi.open} tone="blue"/><Kpi icon={<CheckCircle2/>} title="انجام‌شده" value={kpi.done} tone="ok"/><Kpi icon={<Zap/>} title="فوری" value={kpi.urgent} tone="danger"/><Kpi icon={<Users/>} title="اعضای فعال" value={kpi.team} tone="warn"/></div><div className="split" style={{marginTop:16}}><div className="card"><div className="section"><h2>Pipeline عملیات</h2><span className="pill blue">Live</span></div><div className="kanban">{statuses.map(s=><Column key={s} s={s} tasks={filteredTasks} move={moveTask}/>)}</div></div><div className="card"><h2>پیشنهادهای مدیریتی هوشمند</h2><Insight icon={<Target/>} t="۳ هتل A در وضعیت نیازمند ظرفیت هستند؛ برای امروز تسک فوری بساز."/><Insight icon={<Sparkles/>} t="میانگین انجام تسک‌های پنل بهتر از سایر تیم‌هاست؛ الگوی پیگیری آن‌ها قابل تعمیم است."/><Insight icon={<ShieldCheck/>} t="برای امنیت، رمز همه اعضای جدید را پس از اولین ورود تغییر بده."/><Insight icon={<MessageSquare/>} t="تسک‌های منتظر پاسخ بیش از ۴۸ ساعت باید Escalate شوند."/></div></div></>}
 {tab==='tasks'&&<><div className="section"><h2>Task Center</h2><span className="pill">{filteredTasks.length} تسک</span></div><div className="card"><div className="form"><input placeholder="عنوان تسک" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><select value={draft.hotel} onChange={e=>setDraft({...draft,hotel:e.target.value})}>{hotels.map(h=><option key={h.id}>{h.name}</option>)}</select><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as any})}>{['فوری','بالا','متوسط','پایین'].map(p=><option key={p}>{p}</option>)}</select><select value={draft.assignedTo} onChange={e=>setDraft({...draft,assignedTo:e.target.value})}>{members.filter(m=>m.active).map(m=><option key={m.id}>{m.name}</option>)}</select><input placeholder="ددلاین" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/><textarea placeholder="شرح تسک" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div><div style={{marginTop:12}}><button className="btn brand" onClick={addTask}>ثبت تسک</button></div></div><div style={{marginTop:16}} className="kanban">{statuses.map(s=><Column key={s} s={s} tasks={filteredTasks} move={moveTask}/>)}</div></>}
 {tab==='hotels'&&<><div className="section"><h2>Hotel CRM</h2><button className="btn secondary">Import Excel</button></div><div className="card"><table className="table"><thead><tr><th>هتل</th><th>شهر</th><th>درجه</th><th>اولویت</th><th>وضعیت</th><th>مسئول</th><th>آخرین پیگیری</th></tr></thead><tbody>{hotels.map(h=><tr key={h.id}><td><b>{h.name}</b><div className="label">{h.provider} • {h.rooms} اتاق</div></td><td>{h.city}</td><td>{h.grade}</td><td><span className="pill danger">{h.priority}</span></td><td>{h.status}</td><td>{h.owner}</td><td>{h.lastFollow}</td></tr>)}</tbody></table></div></>}
 {tab==='team'&&<><div className="section"><h2>مدیریت تیم و دسترسی‌ها</h2><span className="pill danger"><Lock size={14}/> فقط مدیر</span></div>{user.role!=='admin'?<div className="empty">این بخش فقط برای مدیر سیستم فعال است.</div>:<><div className="card"><div className="form"><input placeholder="نام عضو" value={newMember.name} onChange={e=>setNewMember({...newMember,name:e.target.value})}/><select value={newMember.role} onChange={e=>setNewMember({...newMember,role:e.target.value as Role})}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input placeholder="زون" value={newMember.zone} onChange={e=>setNewMember({...newMember,zone:e.target.value})}/><input placeholder="سمت" value={newMember.position} onChange={e=>setNewMember({...newMember,position:e.target.value})}/><input placeholder="رمز عبور" value={newMember.password} onChange={e=>setNewMember({...newMember,password:e.target.value})}/></div><div style={{marginTop:12}}><button className="btn brand" onClick={addMember}>افزودن عضو</button></div></div><div className="card" style={{marginTop:16}}><table className="table"><thead><tr><th>نام</th><th>نقش</th><th>زون</th><th>سمت</th><th>KPI</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><b>{m.name}</b></td><td>{roles[m.role]}</td><td>{m.zone}</td><td>{m.position}</td><td><span className="pill ok">{m.score}%</span></td><td>{m.active?<span className="pill ok">فعال</span>:<span className="pill danger">غیرفعال</span>}</td><td><button className="btn secondary" onClick={()=>disableMember(m.id)}>غیرفعال</button></td></tr>)}</tbody></table></div></>}</>}
 {tab==='reports'&&<Reports members={members} tasks={tasks}/>} {tab==='calendar'&&<Placeholder title="تقویم و پیگیری‌ها" items={['یادآوری ددلاین‌ها','پیگیری‌های هفتگی هتل‌های A','Escalation تسک‌های عقب‌افتاده','برنامه تماس کارشناسان']}/>} {tab==='docs'&&<Placeholder title="قرارداد و اسناد" items={['فایل قرارداد هتل','وضعیت تمدید','تاریخ انقضا','ارسال برای مالی','پیوست مستندات']}/>} {tab==='settings'&&<Placeholder title="تنظیمات سیستم" items={['مدیریت وضعیت‌ها','مدیریت دسته‌بندی تسک','مدیریت زون‌ها','Backup تنظیمات','اتصال پیامک و اعلان‌ها']}/>} </main></div>
}
function Kpi({title,value,icon,tone}:{title:string;value:any;icon:any;tone:string}){return <div className="card"><div style={{display:'flex',justifyContent:'space-between'}}><span className={'pill '+tone}>{icon}</span><span className="label">ماه جاری</span></div><div className="num">{value}</div><div className="label">{title}</div></div>}
function Column({s,tasks,move}:{s:string;tasks:Task[];move:any}){const arr=tasks.filter(t=>t.status===s);return <div className="col"><h3>{s} · {arr.length}</h3>{arr.map(t=><div className="task" key={t.id}><h4>{t.title}</h4><div className="label">{t.hotel} • {t.city}</div><div className="meta"><span className="pill blue">{t.category}</span><span className={t.priority==='فوری'?'pill danger':'pill warn'}>{t.priority}</span><span className="pill">{t.assignedTo}</span></div><select style={{width:'100%',marginTop:10,border:'1px solid #e5e7eb',borderRadius:12,padding:8}} value={t.status} onChange={e=>move(t.id,e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>)}{!arr.length&&<div className="empty">تسکی نیست</div>}</div>}
function Insight({icon,t}:{icon:any;t:string}){return <div style={{display:'flex',gap:12,margin:'14px 0',alignItems:'flex-start'}}><span className="pill blue">{icon}</span><p style={{margin:0,fontSize:13,lineHeight:1.9}}>{t}</p></div>}
function Reports({members,tasks}:{members:Member[];tasks:Task[]}){return <><div className="section"><h2>گزارش عملکرد</h2><button className="btn secondary" onClick={()=>{const csv='name,role,score\n'+members.map(m=>`${m.name},${roles[m.role]},${m.score}`).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv])); a.download='iho-report.csv'; a.click()}}>خروجی CSV</button></div><div className="grid kpi"><Kpi icon={<BarChart3/>} title="نرخ انجام" value={`${Math.round(tasks.filter(t=>t.status==='انجام‌شده').length/tasks.length*100)}%`} tone="ok"/><Kpi icon={<Zap/>} title="تسک فوری" value={tasks.filter(t=>t.priority==='فوری').length} tone="danger"/><Kpi icon={<Building2/>} title="هتل فعال" value={seedHotels.length} tone="blue"/><Kpi icon={<Users/>} title="اعضای تیم" value={members.filter(m=>m.active).length} tone="warn"/></div><div className="card" style={{marginTop:16}}><h2>Leaderboard کارشناسان</h2><table className="table"><tbody>{members.filter(m=>m.active).sort((a,b)=>b.score-a.score).map(m=><tr key={m.id}><td><b>{m.name}</b><div className="label">{m.position}</div></td><td>{m.zone}</td><td><span className="pill ok">{m.score}%</span></td></tr>)}</tbody></table></div></>}
function Placeholder({title,items}:{title:string;items:string[]}){return <><div className="section"><h2>{title}</h2><span className="pill blue">Roadmap Ready</span></div><div className="grid kpi">{items.map((x,i)=><div className="card" key={x}><span className="pill blue">{i+1}</span><h3>{x}</h3><p className="label">این ماژول در ساختار IHO OS آماده توسعه عملیاتی و اتصال به Supabase است.</p></div>)}</div></>}
