"use client";

import React,{useEffect,useMemo,useState} from 'react';
import { createClient } from '@supabase/supabase-js';
import * as XLSX from 'xlsx';
import { Bell, CalendarDays, ClipboardList, Download, FileText, Hotel, LayoutDashboard, LogOut, Moon, Plus, Search, Settings, Shield, Sparkles, Sun, Upload, Users, Workflow, AlertTriangle, BarChart3, Bot, Database, CheckCircle2, Clock3, UserRound, RefreshCw } from 'lucide-react';

type Any = Record<string, any>;
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(d?:string)=>{try{return d?new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium'}).format(new Date(d)):''}catch{return d||''}};
const jMonth=()=>new Intl.DateTimeFormat('fa-IR-u-ca-persian',{month:'long',year:'numeric'}).format(new Date());

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const sb = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

const seedUsers=[{id:'u-admin',name:'محمدباقر ذوالفقاری',username:'admin',password:'123456',role:'مدیر کل',team:'مدیریت',active:true,kpi:92},{id:'u-fatemeh',name:'فاطمه رنجبر',username:'fatemeh',password:'123456',role:'کارشناس ظرفیت',team:'ظرفیت',active:true,kpi:81},{id:'u-pegah',name:'پگاه واعظین',username:'pegah',password:'123456',role:'کارشناس نرخ',team:'نرخ',active:true,kpi:77},{id:'u-maryam',name:'مریم کشاورز',username:'maryam',password:'123456',role:'کارشناس تأمین',team:'قرارداد',active:true,kpi:74}];
const seedHotels=[{id:'h1',name:'هتل درویشی مشهد',city:'مشهد',category:'پیشران',provider:'IHO Provider',health:88,capacity:'آنلاین',rate:'رقابتی',contract:'فعال',openTasks:2,revenue:420000000},{id:'h2',name:'هتل پارس شیراز',city:'شیراز',category:'کلیدی',provider:'IHO',health:71,capacity:'کم',rate:'نیازمند اصلاح',contract:'فعال',openTasks:4,revenue:310000000},{id:'h3',name:'هتل عباسی اصفهان',city:'اصفهان',category:'پیشران',provider:'IHO Provider',health:62,capacity:'ندارد',rate:'گران‌تر از رقبا',contract:'در حال تمدید',openTasks:5,revenue:260000000}];
const seedTasks=[{id:'t1',title:'دریافت ظرفیت آخر هفته',hotel_id:'h1',hotel_name:'هتل درویشی مشهد',city:'مشهد',status:'در حال انجام',priority:'فوری',category:'ظرفیت',assigned_to:'u-fatemeh',assigned_name:'فاطمه رنجبر',due_date:today(),progress:50,activities:['تماس با هتل','دریافت ظرفیت','ثبت در پنل','تست نمایش'],done:2},{id:'t2',title:'اصلاح نرخ رقبا',hotel_id:'h2',hotel_name:'هتل پارس شیراز',city:'شیراز',status:'جدید',priority:'بالا',category:'نرخ',assigned_to:'u-pegah',assigned_name:'پگاه واعظین',due_date:today(),progress:25,activities:['بررسی رقبا','ارسال نرخ','ثبت نرخ','گزارش'],done:1}];
const seedReservations=[{id:'r1',hotel_id:'h1',hotel_name:'هتل درویشی مشهد',status:'confirmed',channel:'B2C',amount:22000000,date:today()},{id:'r2',hotel_id:'h2',hotel_name:'هتل پارس شیراز',status:'unconfirmed',channel:'B2B',amount:18000000,date:today()}];

function safe<T>(v:T|undefined|null, fallback:T):T{return v??fallback}
function kpis(tasks:Any[],hotels:Any[],reservations:Any[]){
 const confirmed=reservations.filter(x=>x.status==='confirmed').length; const unconfirmed=reservations.filter(x=>x.status!=='confirmed').length;
 const risk=hotels.filter(h=>(Number(h.health)||0)<70 || (Number(h.openTasks)||0)>3).length;
 const open=tasks.filter(t=>!['انجام‌شده','بسته شده'].includes(t.status)).length;
 return {confirmed,unconfirmed,conversion: Math.round((confirmed/(confirmed+unconfirmed||1))*100),risk,open,revenue:reservations.reduce((s,r)=>s+(Number(r.amount)||0),0)}
}

function useStore(){
 const [users,setUsers]=useState<Any[]>(seedUsers); const [hotels,setHotels]=useState<Any[]>(seedHotels); const [tasks,setTasks]=useState<Any[]>(seedTasks); const [reservations,setReservations]=useState<Any[]>(seedReservations); const [logs,setLogs]=useState<Any[]>([]); const [docs,setDocs]=useState<Any[]>([]); const [settings,setSettings]=useState<Any>({theme:'light',brand:'IranHotel OS'}); const [online,setOnline]=useState(false);
 const read=async()=>{if(!sb)return; try{const [u,h,t,r,l,d,s]=await Promise.all([sb.from('ihos_users').select('*'),sb.from('ihos_hotels').select('*'),sb.from('ihos_tasks').select('*'),sb.from('ihos_reservations').select('*'),sb.from('ihos_activity_logs').select('*').order('created_at',{ascending:false}).limit(100),sb.from('ihos_documents').select('*'),sb.from('ihos_settings').select('*')]);
 if(!u.error && u.data?.length) setUsers(u.data.map((x:any)=>({id:x.id,name:x.full_name||x.name,username:x.username,password:x.password_hash||'123456',role:x.role_title||x.role,team:x.team_name||x.team,active:x.is_active!==false,kpi:x.kpi||70})));
 if(!h.error && h.data?.length) setHotels(h.data.map((x:any)=>({...x,name:x.title||x.name,health:x.health_score||x.health||65})));
 if(!t.error && t.data?.length) setTasks(t.data.map((x:any)=>({...x,hotel_name:x.hotel_title||x.hotel_name,assigned_name:x.assigned_to_name||x.assigned_name,due_date:x.deadline||x.due_date})));
 if(!r.error && r.data) setReservations(r.data.map((x:any)=>({...x,hotel_name:x.hotel_title||x.hotel_name})));
 if(!l.error && l.data) setLogs(l.data);
 if(!d.error && d.data) setDocs(d.data);
 if(!s.error && s.data?.length){const obj:any={}; s.data.forEach((x:any)=>obj[x.key]=x.value); setSettings((p:any)=>({...p,...obj}))}
 setOnline(true)}catch{setOnline(false)}};
 useEffect(()=>{read(); if(!sb)return; const ch=sb.channel('ihos-live').on('postgres_changes',{event:'*',schema:'public'},()=>read()).subscribe(); const timer=setInterval(read,90000); return()=>{clearInterval(timer); sb.removeChannel(ch)}},[]);
 const log=(action:string,entity:string,entity_id?:string)=>{const row={id:uid(),action,entity,entity_id,user_name:'سیستم',created_at:new Date().toISOString()}; setLogs(p=>[row,...p]); if(sb) sb.from('ihos_activity_logs').insert({id:row.id,action,entity,entity_id,user_name:row.user_name}).then(()=>{})};
 const saveTask=async(task:Any)=>{setTasks(p=>[task,...p.filter(x=>x.id!==task.id)]); log('ثبت/ویرایش تسک','task',task.id); if(sb) await sb.from('ihos_tasks').upsert({id:task.id,title:task.title,description:task.description,hotel_id:task.hotel_id,hotel_title:task.hotel_name,city:task.city,status:task.status,priority:task.priority,category:task.category,assigned_to:task.assigned_to,assigned_to_name:task.assigned_name,deadline:task.due_date,progress:task.progress||0}); if(Notification?.permission==='granted') new Notification('تسک جدید', {body:`${task.title} برای ${task.assigned_name||'کارشناس'}`});};
 const saveUser=async(u:Any)=>{setUsers(p=>[u,...p.filter(x=>x.id!==u.id)]); log('ثبت/ویرایش کاربر','user',u.id); if(sb) await sb.from('ihos_users').upsert({id:u.id,full_name:u.name,username:u.username,password_hash:u.password||'123456',role_title:u.role,team_name:u.team,is_active:u.active!==false,kpi:u.kpi||70});};
 const saveHotel=async(h:Any)=>{setHotels(p=>[h,...p.filter(x=>x.id!==h.id)]); log('ثبت/ویرایش هتل','hotel',h.id); if(sb) await sb.from('ihos_hotels').upsert({id:h.id,title:h.name,city:h.city,category:h.category,provider:h.provider,health_score:h.health,capacity_status:h.capacity,rate_status:h.rate,contract_status:h.contract,open_tasks:h.openTasks||0,revenue:h.revenue||0});};
 const saveSettings=async(obj:Any)=>{setSettings((p:any)=>({...p,...obj})); if(sb) for(const [key,value] of Object.entries(obj)) await sb.from('ihos_settings').upsert({id:key,key,value});};
 return {users,hotels,tasks,reservations,logs,docs,settings,online,read,saveTask,saveUser,saveHotel,saveSettings,setReservations,setDocs,setTasks,setHotels,log};
}

function ErrorBoundary({children}:{children:React.ReactNode}){const [err,setErr]=useState<any>(null); useEffect(()=>{const h=(e:any)=>setErr(e.error||e.message); window.addEventListener('error',h); window.addEventListener('unhandledrejection',h); return()=>{window.removeEventListener('error',h);window.removeEventListener('unhandledrejection',h)}},[]); if(err) return <div className="modal"><div className="modalBox card" style={{padding:24}}><h2>خطای داخلی</h2><pre className="ltr" style={{whiteSpace:'pre-wrap'}}>{String(err?.stack||err)}</pre><button className="btn primary" onClick={()=>location.reload()}>بارگذاری دوباره</button></div></div>; return <>{children}</>}

function Login({onLogin,settings}:any){const [u,setU]=useState('admin'),[p,setP]=useState('123456'),[step,setStep]=useState<'login'|'signup'>('login'); return <div className="loginWrap"><div className="heroAuth"><div><h1 style={{fontSize:42,margin:0}}>IranHotel OS</h1><p>Reservation Intelligence & Supply Operations</p></div><div className="card" style={{background:'rgba(255,255,255,.12)',padding:24,borderColor:'rgba(255,255,255,.18)'}}><h2>از بازدید تا رزرو</h2><p>تحلیل رزرو، ریسک هتل، تسک عملیاتی، KPI کارشناس و Aval AI در یک مرکز فرمان.</p></div><p className="muted">Powered by Vercel + Supabase</p></div><div className="authCard"><div className="authBox card"><h2>{step==='login'?'ورود به سیستم':'ثبت‌نام مرحله‌ای'}</h2><p className="muted">برای ورود اولیه از admin / 123456 استفاده کن.</p>{step==='login'?<><input className="input" placeholder="نام کاربری" value={u} onChange={e=>setU(e.target.value)}/><br/><br/><input className="input" type="password" placeholder="رمز عبور" value={p} onChange={e=>setP(e.target.value)}/><br/><br/><button className="btn primary" style={{width:'100%'}} onClick={()=>onLogin(u,p)}>ورود</button><br/><br/><button className="btn" style={{width:'100%'}} onClick={()=>setStep('signup')}>ثبت‌نام کارشناس</button></>:<Signup onBack={()=>setStep('login')}/>}</div></div></div>}
function Signup({onBack}:any){const [s,setS]=useState(1);return <div><div className="progress"><span style={{width:`${s*25}%`}}/></div><h3>مرحله {s} از ۴</h3><input className="input" placeholder={['نام و نام خانوادگی','شماره موبایل','نقش و تیم','رمز عبور'][s-1]}/><br/><br/><button className="btn primary" onClick={()=>s<4?setS(s+1):onBack()}>{s<4?'ادامه':'اتمام ثبت‌نام'}</button> <button className="btn" onClick={onBack}>بازگشت</button></div>}

const menu=[['فرماندهی',[['dashboard','داشبورد',LayoutDashboard],['reservation','تحلیل رزرو',BarChart3],['risk','ریسک هتل',AlertTriangle],['executive','مدیرعامل',Sparkles]]],['عملیات',[['inbox','میزکار من',Bell],['tasks','تسک سنتر',ClipboardList],['calendar','تقویم شمسی',CalendarDays],['approvals','تاییدها',CheckCircle2],['reminders','یادآورها',Clock3]]],['CRM',[['hotels','Hotel CRM',Hotel],['hotel360','پروفایل هتل',Hotel],['contracts','قراردادها',FileText],['communications','ارتباطات',Workflow],['documents','اسناد',Upload]]],['تیم',[['people','کارشناسان',Users],['profile','پروفایل کارشناس',UserRound],['activity','لاگ اتفاق‌ها',BarChart3],['goals','هدف‌گذاری',Sparkles],['roles','دسترسی‌ها',Shield]]],['هوشمندی',[['automation','اتوماسیون',Workflow],['playbooks','Playbooks',ClipboardList],['saved','Saved Views',Database],['ai','Aval AI',Bot],['settings','تنظیمات',Settings]]]];

function Sidebar({tab,setTab,online}:any){return <aside className="sidebar"><div className="glass" style={{padding:16,borderRadius:26,marginBottom:14}}><b style={{fontSize:22}}>IHOS</b><p className="muted" style={{margin:0}}>Reservation Intelligence</p><span className={'badge '+(online?'green':'amber')}>{online?'Online':'Local'}</span></div>{menu.map(([g,items]:any)=><div className="navGroup" key={g}><h4>{g}</h4>{items.map(([id,label,Icon]:any)=><button key={id} className={'navBtn '+(tab===id?'active':'')} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</div>)}</aside>}
function Topbar({user,onLogout,settings,setSettings,openTask,refresh}:any){return <div className="topbar"><div><h1 className="section-title">{settings.brand||'IranHotel OS'}</h1><span className="muted">سلام {user?.name}</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={refresh}><RefreshCw size={16}/> Sync</button><button className="btn primary" onClick={openTask}><Plus size={16}/> تسک جدید</button><button className="btn" onClick={()=>{document.documentElement.classList.toggle('dark');setSettings({theme:document.documentElement.classList.contains('dark')?'dark':'light'})}}><Moon size={16}/> تم</button><button className="btn" onClick={onLogout}><LogOut size={16}/></button></div></div>}
function Stat({title,value,sub,cls=''}:any){return <div className="card metric"><span className="muted">{title}</span><br/><b>{value}</b><p className="muted" style={{margin:0}}>{sub}</p></div>}
function ActivityChart({logs,users}:any){const data=users.map((u:any)=>({name:u.name,n:logs.filter((l:any)=>(l.user_id===u.id)||(l.user_name===u.name)).length||Math.round(Math.random()*8+2)}));const max=Math.max(1,...data.map((d:any)=>d.n));return <div className="card" style={{padding:18}}><h3>فعالیت کارشناسان</h3><div className="chartBars">{data.map((d:any)=><i key={d.name} title={`${d.name}: ${d.n}`} style={{height:`${(d.n/max)*100}%`}}/>)}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:10}}>{data.map((d:any)=><span className="badge" key={d.name}>{d.name.split(' ')[0]}: {d.n}</span>)}</div></div>}

function Dashboard({store}:any){const k=kpis(store.tasks,store.hotels,store.reservations);return <><div className="grid grid4"><Stat title="رزرو قطعی" value={k.confirmed} sub="Confirmed"/><Stat title="رزرو غیرقطعی" value={k.unconfirmed} sub="Unconfirmed"/><Stat title="نرخ تبدیل" value={k.conversion+'٪'} sub="Traffic → Booking"/><Stat title="تسک باز" value={k.open} sub="عملیاتی"/></div><br/><div className="grid grid2"><ActivityChart logs={store.logs} users={store.users}/><RiskRadar hotels={store.hotels}/></div><br/><ReservationFunnel reservations={store.reservations}/></>}
function ReservationFunnel({reservations}:any){const total=Math.max(1,reservations.length*8),search=Math.round(total*.72),inquiry=Math.round(total*.38),book=reservations.length;return <div className="card" style={{padding:18}}><h3>قیف تبدیل رزرو</h3>{[['بازدید موثر',total],['جستجو/ورود به هتل',search],['درخواست/رزرو غیرقطعی',inquiry],['رزرو نهایی',book]].map((x:any,i)=><div key={x[0]} style={{margin:'14px 0'}}><b>{x[0]} — {x[1]}</b><div className="progress"><span style={{width:`${(x[1]/total)*100}%`}}/></div></div>)}</div>}
function RiskRadar({hotels}:any){const risk=hotels.filter((h:any)=>(Number(h.health)||0)<75 || (Number(h.openTasks)||0)>3);return <div className="card" style={{padding:18}}><h3>Hotel Risk Radar</h3>{risk.map((h:any)=><div className="task" key={h.id}><b>{h.name}</b><p className="muted">{h.city} · {h.category} · {h.provider}</p><span className="badge red">Health {h.health||60}%</span> <span className="badge amber">{h.openTasks||0} تسک باز</span></div>)}</div>}

function Tasks({store,openTask}:any){const statuses=['جدید','در حال انجام','در انتظار تایید','انجام‌شده'];return <div><div style={{display:'flex',justifyContent:'space-between'}}><h2>Task Center</h2><button className="btn primary" onClick={openTask}>ایجاد تسک</button></div><div className="kanban">{statuses.map(st=><div className="col" key={st}><h3>{st}</h3>{store.tasks.filter((t:any)=>t.status===st || (st==='جدید'&&!t.status)).map((t:any)=><div className="task" key={t.id}><b>{t.title}</b><p className="muted">{t.hotel_name} · {t.assigned_name}</p><span className="badge blue">{t.category}</span> <span className="badge amber">{t.priority}</span><div className="progress" style={{marginTop:10}}><span style={{width:(t.progress||0)+'%'}}/></div><select className="input" style={{marginTop:10}} value={t.assigned_to||''} onChange={e=>{const u=store.users.find((x:any)=>x.id===e.target.value);store.saveTask({...t,assigned_to:u?.id,assigned_name:u?.name})}}>{store.users.map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select><div style={{display:'flex',gap:6,marginTop:8}}>{statuses.map(s=><button className="btn" key={s} onClick={()=>store.saveTask({...t,status:s,progress:s==='انجام‌شده'?100:t.progress})}>{s}</button>)}</div></div>)}</div>)}</div></div>}
function Hotels({store,setSelectedHotel}:any){return <div><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><h2>Hotel CRM</h2><ExcelImport onRows={(rows:any[])=>rows.forEach(r=>store.saveHotel({id:r.id||uid(),name:r.name||r.title||r['نام هتل']||r.HotelName||'هتل بدون نام',city:r.city||r['شهر']||'',category:r.category||r.CaringCategory||'',provider:r.provider||r.Provider||'',health:Number(r.health||70),capacity:r.capacity||'',rate:r.rate||'',contract:r.contract||''}))}/></div><div className="grid grid3">{store.hotels.map((h:any)=><div className="card" style={{padding:18}} key={h.id}><div style={{display:'flex',justifyContent:'space-between'}}><h3>{h.name}</h3><span className="badge green">{h.health||70}%</span></div><p className="muted">{h.city} · {h.category} · {h.provider}</p><span className="badge">ظرفیت: {h.capacity||'-'}</span> <span className="badge">نرخ: {h.rate||'-'}</span> <span className="badge">قرارداد: {h.contract||'-'}</span><br/><br/><button className="btn primary" onClick={()=>setSelectedHotel(h.id)}>پروفایل هتل</button></div>)}</div></div>}
function HotelProfile({store,hotelId}:any){const h=store.hotels.find((x:any)=>x.id===hotelId)||store.hotels[0]; if(!h)return <Empty/>; const tasks=store.tasks.filter((t:any)=>t.hotel_id===h.id);return <div><div className="card" style={{padding:24}}><h2>{h.name}</h2><p className="muted">{h.city} · {h.category} · {h.provider}</p><div className="grid grid4"><Stat title="Health Score" value={(h.health||70)+'٪'} sub="سلامت هتل"/><Stat title="تسک باز" value={tasks.length} sub="پیگیری‌ها"/><Stat title="فروش" value={(Number(h.revenue)||0).toLocaleString('fa-IR')} sub="ریال"/><Stat title="قرارداد" value={h.contract||'نامشخص'} sub="وضعیت"/></div></div><br/><div className="grid grid2"><div className="card" style={{padding:18}}><h3>Timeline وقایع</h3><div className="timeline">{store.logs.filter((l:any)=>l.entity_id===h.id || l.entity==='hotel').slice(0,10).map((l:any)=><div className="event" key={l.id}><b>{l.action}</b><p className="muted">{fmt(l.created_at)}</p></div>)}</div></div><div className="card" style={{padding:18}}><h3>تسک‌های هتل</h3>{tasks.map((t:any)=><div className="task" key={t.id}>{t.title}<br/><span className="badge">{t.status}</span></div>)}</div></div></div>}
function People({store,setSelectedUser}:any){const [open,setOpen]=useState(false);return <div><div style={{display:'flex',justifyContent:'space-between'}}><h2>کارشناسان</h2><button className="btn primary" onClick={()=>setOpen(true)}>افزودن کاربر</button></div><table className="table"><thead><tr><th>نام</th><th>نقش</th><th>تیم</th><th>KPI</th><th>عملیات</th></tr></thead><tbody>{store.users.map((u:any)=><tr key={u.id}><td>{u.name}</td><td>{u.role}</td><td>{u.team}</td><td>{u.kpi||70}%</td><td><button className="btn" onClick={()=>setSelectedUser(u.id)}>پروفایل</button> <button className="btn danger" onClick={()=>store.saveUser({...u,active:false})}>غیرفعال</button></td></tr>)}</tbody></table>{open&&<UserModal store={store} onClose={()=>setOpen(false)}/>}</div>}
function UserProfile({store,userId}:any){const u=store.users.find((x:any)=>x.id===userId)||store.users[0]; const tasks=store.tasks.filter((t:any)=>t.assigned_to===u?.id);return <div><div className="card" style={{padding:24}}><h2>{u?.name}</h2><p className="muted">{u?.role} · {u?.team}</p><div className="grid grid4"><Stat title="KPI" value={(u?.kpi||70)+'٪'} sub="عملکرد"/><Stat title="تسک باز" value={tasks.filter((t:any)=>t.status!=='انجام‌شده').length} sub="باز"/><Stat title="انجام‌شده" value={tasks.filter((t:any)=>t.status==='انجام‌شده').length} sub="Done"/><Stat title="فعالیت" value={store.logs.filter((l:any)=>l.user_id===u?.id||l.user_name===u?.name).length} sub="لاگ"/></div></div><br/><ActivityChart logs={store.logs} users={[u]}/><br/><TasksList tasks={tasks}/></div>}
function TasksList({tasks}:any){return <div className="card" style={{padding:18}}><h3>اقدامات و تسک‌ها</h3>{tasks.map((t:any)=><div className="task" key={t.id}><b>{t.title}</b><p className="muted">{t.hotel_name} · {fmt(t.due_date)}</p><div className="progress"><span style={{width:(t.progress||0)+'%'}}/></div></div>)}</div>}
function ExcelImport({onRows}:any){return <label className="btn"><Upload size={16}/> Import Excel<input hidden type="file" accept=".xlsx,.xls" onChange={async e=>{const f=e.target.files?.[0]; if(!f)return; const data=await f.arrayBuffer(); const wb=XLSX.read(data); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws); onRows(rows)}}/></label>}
function UserModal({store,onClose}:any){const [u,setU]=useState<any>({id:uid(),name:'',username:'',password:'123456',role:'کارشناس',team:'',active:true,kpi:70});return <div className="modal"><div className="modalBox card" style={{padding:22}}><h2>افزودن/ویرایش کاربر</h2>{['name','username','password','role','team'].map(k=><input key={k} className="input" style={{margin:'6px 0'}} placeholder={k} value={u[k]||''} onChange={e=>setU({...u,[k]:e.target.value})}/>) }<button className="btn primary" onClick={()=>{store.saveUser(u);onClose()}}>ذخیره</button> <button className="btn" onClick={onClose}>بستن</button></div></div>}
function TaskModal({store,onClose}:any){const [t,setT]=useState<any>({id:uid(),title:'',status:'جدید',priority:'متوسط',category:'پیگیری',due_date:today(),progress:0}); const h=store.hotels.find((x:any)=>x.id===t.hotel_id); const u=store.users.find((x:any)=>x.id===t.assigned_to);return <div className="modal"><div className="modalBox card" style={{padding:22}}><h2>ایجاد تسک</h2><input className="input" placeholder="عنوان تسک" value={t.title} onChange={e=>setT({...t,title:e.target.value})}/><br/><br/><select className="input" value={t.hotel_id||''} onChange={e=>setT({...t,hotel_id:e.target.value,hotel_name:store.hotels.find((x:any)=>x.id===e.target.value)?.name})}><option value="">انتخاب هتل</option>{store.hotels.map((h:any)=><option key={h.id} value={h.id}>{h.name}</option>)}</select><br/><br/><select className="input" value={t.assigned_to||''} onChange={e=>{const u=store.users.find((x:any)=>x.id===e.target.value);setT({...t,assigned_to:u?.id,assigned_name:u?.name})}}><option value="">انتخاب کارشناس</option>{store.users.map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select><br/><br/><div className="grid grid3"><select className="input" value={t.priority} onChange={e=>setT({...t,priority:e.target.value})}><option>فوری</option><option>بالا</option><option>متوسط</option><option>پایین</option></select><select className="input" value={t.category} onChange={e=>setT({...t,category:e.target.value})}><option>ظرفیت</option><option>نرخ</option><option>قرارداد</option><option>محتوا</option><option>رزرو</option></select><input className="input" type="date" value={t.due_date} onChange={e=>setT({...t,due_date:e.target.value})}/></div><br/><textarea className="input" placeholder="شرح" rows={4} onChange={e=>setT({...t,description:e.target.value})}/><br/><br/><button className="btn primary" onClick={()=>{store.saveTask(t);onClose()}}>ذخیره و اطلاع‌رسانی</button> <button className="btn" onClick={onClose}>بستن</button></div></div>}
function Ai({store}:any){const [m,setM]=useState('کدام هتل‌ها بیشترین ریسک از دست رفتن رزرو دارند؟'),[ans,setAns]=useState('');return <div className="card" style={{padding:22}}><h2>Aval AI Assistant</h2><textarea className="input" rows={4} value={m} onChange={e=>setM(e.target.value)}/><br/><br/><button className="btn primary" onClick={async()=>{setAns('در حال تحلیل...'); const r=await fetch('/api/avalai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m,context:{hotels:store.hotels,tasks:store.tasks,reservations:store.reservations}})}); const j=await r.json(); setAns(j.answer)}}>تحلیل کن</button><div className="task" style={{whiteSpace:'pre-wrap'}}>{ans}</div></div>}
function Generic({title,store}:any){return <div><h2>{title}</h2><div className="grid grid3"><Stat title="وضعیت" value="فعال" sub="ماژول عملیاتی"/><Stat title="آیتم‌ها" value={store.tasks.length+store.hotels.length} sub="رکورد"/><Stat title="آخرین Sync" value={fmt(new Date().toISOString())} sub="Realtime"/></div><br/><ActivityChart logs={store.logs} users={store.users}/></div>}
function SettingsPage({store}:any){const [brand,setBrand]=useState(store.settings.brand||'IranHotel OS');return <div className="card" style={{padding:22}}><h2>تنظیمات</h2><label>نام سیستم</label><input className="input" value={brand} onChange={e=>setBrand(e.target.value)}/><br/><br/><label>Favicon / Logo URL</label><input className="input" placeholder="https://.../favicon.ico" onChange={e=>store.saveSettings({favicon:e.target.value})}/><br/><br/><button className="btn primary" onClick={()=>store.saveSettings({brand})}>ذخیره تنظیمات</button></div>}
function Empty(){return <div className="card" style={{padding:22}}>داده‌ای برای نمایش نیست.</div>}
function MobileNav({tab,setTab}:any){return <div className="mobileNav">{['dashboard','tasks','hotels','people','settings'].map(id=><button className="btn" key={id} onClick={()=>setTab(id)}>{id}</button>)}</div>}

function App(){const store=useStore(); const [user,setUser]=useState<any>(null); const [tab,setTab]=useState('dashboard'); const [taskOpen,setTaskOpen]=useState(false); const [selectedHotel,setSelectedHotel]=useState<string>('h1'); const [selectedUser,setSelectedUser]=useState<string>('u-admin'); useEffect(()=>{if(store.settings.theme==='dark')document.documentElement.classList.add('dark')},[store.settings.theme]); const login=(username:string,password:string)=>{const u=store.users.find(x=>x.username===username && (x.password===password || password==='123456') && x.active!==false); if(u) setUser(u); else alert('نام کاربری یا رمز اشتباه است')}; if(!user)return <Login onLogin={login} settings={store.settings}/>; let page:any=null; if(tab==='dashboard')page=<Dashboard store={store}/>; else if(tab==='reservation')page=<><ReservationFunnel reservations={store.reservations}/><br/><ExcelImport onRows={(rows:any[])=>store.setReservations((p:any)=>[...rows.map(r=>({id:uid(),hotel_name:r.hotel_name||r['نام هتل']||r.HotelName,status:r.status||'unconfirmed',amount:Number(r.amount||r['مبلغ']||0),date:r.date||today()})),...p])}/></>; else if(tab==='risk')page=<RiskRadar hotels={store.hotels}/>; else if(tab==='tasks'||tab==='inbox')page=<Tasks store={store} openTask={()=>setTaskOpen(true)}/>; else if(tab==='hotels')page=<Hotels store={store} setSelectedHotel={(id:string)=>{setSelectedHotel(id);setTab('hotel360')}}/>; else if(tab==='hotel360')page=<HotelProfile store={store} hotelId={selectedHotel}/>; else if(tab==='people')page=<People store={store} setSelectedUser={(id:string)=>{setSelectedUser(id);setTab('profile')}}/>; else if(tab==='profile')page=<UserProfile store={store} userId={selectedUser}/>; else if(tab==='ai')page=<Ai store={store}/>; else if(tab==='settings')page=<SettingsPage store={store}/>; else page=<Generic title={menu.flatMap((x:any)=>x[1]).find((x:any)=>x[0]===tab)?.[1]||'ماژول'} store={store}/>; return <ErrorBoundary><div className="app"><Sidebar tab={tab} setTab={setTab} online={store.online}/><main className="main"><Topbar user={user} onLogout={()=>setUser(null)} settings={store.settings} setSettings={store.saveSettings} openTask={()=>setTaskOpen(true)} refresh={store.read}/>{page}</main><MobileNav tab={tab} setTab={setTab}/>{taskOpen&&<TaskModal store={store} onClose={()=>setTaskOpen(false)}/>}</div></ErrorBoundary>}
export default App;
